--
-- PostgreSQL database dump
--

\restrict UdkMZFzhJbg11GAu4ikOKzn5RU9qkFRYswURPgnzPHu6gszUjdIkcnd4sBggMPr

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Cakes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Cakes" (
    "Id" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "ImageUrl" character varying(500) NOT NULL,
    "ThumbnailUrl" character varying(500) NOT NULL,
    "CategorySlug" character varying(100) NOT NULL,
    "SubCategory" character varying(100),
    "IsFeatured" boolean NOT NULL,
    "Description" character varying(2000),
    "FillingId" integer
);


--
-- Name: Cakes_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Cakes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cakes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Categories" (
    "Id" integer NOT NULL,
    "Slug" character varying(100) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "SortOrder" text NOT NULL
);


--
-- Name: Categories_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ContactSettings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ContactSettings" (
    "Id" integer NOT NULL,
    "Phone" character varying(50) NOT NULL,
    "AdditionalPhone" character varying(50),
    "Email" character varying(200) NOT NULL,
    "Address" character varying(500),
    "MapUrl" character varying(1000)
);


--
-- Name: ContactSettings_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ContactSettings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ContactSettings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ContentBlocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ContentBlocks" (
    "Id" integer NOT NULL,
    "PageId" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Text" text NOT NULL,
    "ImageUrl" character varying(500),
    "SortOrder" integer NOT NULL
);


--
-- Name: ContentBlocks_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ContentBlocks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ContentBlocks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Fillings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Fillings" (
    "Id" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "ImageUrl" character varying(500) NOT NULL,
    "HasCrossSection" boolean NOT NULL
);


--
-- Name: Fillings_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Fillings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Fillings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Orders" (
    "Id" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CustomerName" character varying(200) NOT NULL,
    "CustomerPhone" character varying(50) NOT NULL,
    "CustomerEmail" character varying(200),
    "CakeId" integer,
    "CustomCakeDescription" character varying(2000),
    "FillingId" integer,
    "Weight" numeric(10,2),
    "DeliveryDate" timestamp with time zone,
    "DeliveryAddress" character varying(500),
    "Status" character varying(50) NOT NULL,
    "Comment" character varying(1000)
);


--
-- Name: Orders_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Orders" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Orders_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Pages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Pages" (
    "Id" integer NOT NULL,
    "Slug" character varying(100) NOT NULL,
    "Title" character varying(200) NOT NULL,
    "MetaDescription" character varying(500) NOT NULL,
    "Heading" character varying(200) NOT NULL,
    "Subheading" character varying(500),
    "Content" text
);


--
-- Name: Pages_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Pages" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Pages_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SliderItems; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."SliderItems" (
    "Id" integer NOT NULL,
    "ImageUrl" character varying(500) NOT NULL,
    "Title" character varying(200),
    "Subtitle" character varying(500),
    "SortOrder" integer NOT NULL
);


--
-- Name: SliderItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."SliderItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SliderItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Testimonials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Testimonials" (
    "Id" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Author" character varying(200) NOT NULL,
    "Email" character varying(200),
    "Text" character varying(4000) NOT NULL,
    "Response" character varying(4000),
    "IsApproved" boolean NOT NULL
);


--
-- Name: Testimonials_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Testimonials" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Testimonials_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Name: __MigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__MigrationsHistory" (
    "Id" integer NOT NULL,
    "MigrationName" character varying(255) NOT NULL,
    "AppliedDate" timestamp without time zone NOT NULL,
    "Details" text
);


--
-- Name: __MigrationsHistory_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."__MigrationsHistory_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: __MigrationsHistory_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."__MigrationsHistory_Id_seq" OWNED BY public."__MigrationsHistory"."Id";


--
-- Name: __MigrationsHistory Id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__MigrationsHistory" ALTER COLUMN "Id" SET DEFAULT nextval('public."__MigrationsHistory_Id_seq"'::regclass);


--
-- Data for Name: Cakes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Cakes" ("Id", "Name", "ImageUrl", "ThumbnailUrl", "CategorySlug", "SubCategory", "IsFeatured", "Description", "FillingId") FROM stdin;
54	Торт № 1 д.	d11.png	sm-d11.png	detskie	3D	f	от 2,5 кг	\N
55	Торт № 2 д.	d10.png	sm-d10.png	detskie	3D	f	от 3 кг	\N
68	Торт № 1 п.	p17.png	sm-p17.png	prazdnichnye	3D	t	от 3 кг.	\N
69	Торт № 2 п.	p4.png	sm-p4.png	prazdnichnye	3D	f	от 4 кг.	\N
70	Торт № 3 п.	p1.png	sm-p1.png	prazdnichnye	3d	t	от 3 кг.	\N
74	Торт № 6 п.	p6.png	sm-p6.png	prazdnichnye	risovannye	f	от 2,5 кг 	\N
83	Торт № 14 п.	p15.png	sm-p15.png	prazdnichnye	NULL	f	от 2,5 кг 	\N
86	Торт № 15 п.	p19.png	sm-p19.png	prazdnichnye	NULL	t	от 2,5 кг 	\N
87	Торт № 1 к.	k1.png	sm-k1.png	corporativnye	NULL	t	от 3 кг., 1900 руб/кг.	\N
88	Торт № 1 с.	s1.png	sm-s1.png	svadebnye	NULL	f	от 2 кг.	\N
89	Торт № 2 к.	k2.png	sm-k2.png	corporativnye	NULL	f	от 3 кг., 1800 руб/кг.	\N
90	Торт № 3 к.	k3.png	sm-k3.png	corporativnye	NULL	f	от 3 кг., 1900 руб/кг.	\N
93	Торт № 4 к.	k6.png	sm-k6.png	corporativnye	NULL	f	от 3 кг., 1900 руб/кг.	\N
95	Торт № 5 к.	k8.png	sm-k8.png	corporativnye	NULL	f	от 3 кг., 1900 руб/кг.	\N
96	Торт № 6 к.	k9.png	sm-k9.png	corporativnye	NULL	t	от 3 кг., 1800 руб/кг.	\N
97	Торт № 7 к.	k10.png	sm-k10.png	corporativnye	NULL	f	от 3 кг., 1800 руб/кг.	\N
98	Торт № 8 к.	k11.png	sm-k11.png	corporativnye	NULL	f	от 3 кг., 1900 руб/кг.	\N
99	Торт № 9 к.	k12.png	sm-k12.png	corporativnye	NULL	f	от 3 кг., 1800 руб/кг.	\N
100	Торт № 10 к.	k13.png	sm-k13.png	corporativnye	NULL	t	от 4 кг., 1800 руб/кг.	\N
102	Торт № 2 с.	s2.png	sm-s2.png	svadebnye	NULL	t	от 6 кг.	\N
105	Торт № 3 с.	s5.png	sm-s5.png	svadebnye	NULL	t	от 3 кг.	\N
106	Торт № 4 с.	s6.png	sm-s6.png	svadebnye	NULL	t	от 3 кг.	\N
108	Торт № 5 с.	s8.png	sm-s8.png	svadebnye	NULL	t	от 3,5 кг	\N
109	Торт № 6 с.	s9.png	sm-s9.png	svadebnye	NULL	f	от 4 кг.	\N
110	Торт № 7 с.	s10.png	sm-s10.png	svadebnye	NULL	f	от 3 кг.	\N
112	Торт № 8 с.	s12.png	sm-s12.png	svadebnye	NULL	f	от 8 кг.	\N
114	Торт № 9 с.	s14.png	sm-s14.png	svadebnye	NULL	f	от 6 кг	\N
115	Торт № 10 с.	s15.png	sm-s15.png	svadebnye	NULL	f	от 2,5кг.,	\N
116	Торт № 11 с.	s16.png	sm-s16.png	svadebnye	NULL	f	от 6 кг	\N
119	Торт № 12 с.	s19.png	sm-s19.png	svadebnye	NULL	f	от 4 кг.	\N
120	Торт № 13 с.	s20.png	sm-s20.png	svadebnye	NULL	f	от 11 кг	\N
121	Торт № 14 с 	s21.png	sm-s21.png	svadebnye	NULL	t	от 3 кг	\N
124	Торт № 15 с.	s24.png	sm-s24.png	svadebnye	NULL	t	от 9 кг.	\N
125	Торт № 16 п.	p20.png	sm-p20.png	prazdnichnye	3d	f	от 2,5 кг 	\N
135	Торт № 16 с.	s25.png	sm-s25.png	svadebnye	NULL	t	от 6 кг.	\N
137	Торт № 17 с.	s27.png	sm-s27.png	svadebnye	NULL	t	от 8 кг.,	\N
138	Торт № 18 с.	s28.png	sm-s28.png	svadebnye	NULL	f	от 4,5 кг	\N
139	Торт № 19 с.	s29.png	sm-s29.png	svadebnye	NULL	t	от 6 кг.,	\N
142	Торт № 20 с.	s32.png	sm-s32.png	svadebnye	NULL	t	от 5 кг.	\N
144	Торт № 21 с.	s34.png	sm-s34.png	svadebnye	NULL	t	от 4 кг	\N
145	Торт № 22 с.	awtjnii.png	sm-awtjnii.png	svadebnye	NULL	t	от 2,5кг.	\N
146	Торт № 23 с.	dfbntumi.png	sm-dfbntumi.png	svadebnye	NULL	t	от 3,5 кг.	\N
149	Торт № 24 с.	dfunyili.png	sm-dfunyili.png	svadebnye	NULL	t	от 7 кг	\N
154	Торт № 25 с.	sdftnhtumi.png	sm-sdftnhtumi.png	svadebnye	NULL	t	от 2,5 кг.	\N
156	Торт № 17 п.	szdfhfjdtyi.png	sm-szdfhfjdtyi.png	prazdnichnye	NULL	f	от 3 кг.	\N
157	Торт № 18 п.	vxbnjnki.png	sm-vxbnjnki.png	prazdnichnye	NULL	f	от 2,5 кг	\N
159	Торт № 19 п.	asftrwexdfgfgu.png	sm-asftrwexdfgfgu.png	prazdnichnye	yagody	f	от 3 кг.	\N
161	Торт № 20 п.	aweguikfre.png	sm-aweguikfre.png	prazdnichnye	2D	f	от 2 кг, 1400 руб/кг.	\N
162	Торт № 21 п.	dftgnjy.png	sm-dftgnjy.png	prazdnichnye	2D	f	от 2 кг, 1700 руб/кг.	\N
163	Торт № 11 к.	gkasdfdxvgh.png	sm-gkasdfdxvgh.png	corporativnye	3D	f	от 3 кг., 1900 руб/кг.	\N
167	Торт № 26 с.	sdfghweryifd.png	sm-sdfghweryifd.png	svadebnye	NULL	f	от 2 кг 	\N
170	Торт № 9 д.	shjiogxea.png	sm-shjiogxea.png	detskie	3D	t	от 3 кг	\N
171	Торт № 27 с.	sntgsrtft.png	sm-sntgsrtft.png	svadebnye	NULL	f	от 9 кг	\N
173	Торт № 22 п.	zsdrhjioyhe.png	sm-zsdrhjioyhe.png	prazdnichnye	yagody	f	от 3 кг 1900 руб/кг.	\N
174	Торт № 28 с.	asrbvcayt.png	sm-asrbvcayt.png	svadebnye	NULL	f	от 7 кг.,	\N
175	Торт № 29 с.	axcevbnujn.png	sm-axcevbnujn.png	svadebnye	NULL	f	от 5 кг.	\N
177	Торт № 30 с.	dsgrghg.png	sm-dsgrghg.png	svadebnye	NULL	f	от 7 кг.	\N
178	Торт № 23 п.	rtbheafcuyt.png	sm-rtbheafcuyt.png	prazdnichnye	3D	f	от 2,5 кг 2000 руб/кг.	\N
179	Торт № 31 с.	sdgiuoasdgchrdtgfbgd.png	sm-sdgiuoasdgchrdtgfbgd.png	svadebnye	NULL	f	от 6 кг	\N
180	Торт № 12 к.	xcfewrvbt.png	sm-xcfewrvbt.png	corporativnye	NULL	f	от 3 кг., 1900 руб/кг.	\N
181	Торт № 13 к.	asdfghjk.png	sm-asdfghjk.png	corporativnye	NULL	f	от 3 кг., 1900 руб/кг.	\N
182	Торт № 14 к.	eawduji.png	sm-eawduji.png	corporativnye	NULL	f	от 3 кг., 1800 руб/кг.	\N
184	Торт № 24 п.	IMGP0001i.png	sm-IMGP0001i.png	prazdnichnye	3D	f	от 3 кг., 1900 руб/кг.	\N
185	Торт № 11 д.	IMGP0001ii.png	sm-IMGP0001ii.png	detskie	NULL	f	от 2 кг	\N
188	Торт № 25 п.	IMGP0002i.png	sm-IMGP0002i.png	prazdnichnye	NULL	f	от 2,5 кг., 2000 руб/кг.	\N
189	Торт № 26 п.	IMGP0002ii.png	sm-IMGP0002ii.png	prazdnichnye	2D	f	от 2 кг 1400 руб/кг.	\N
191	Торт № 32 с.	IMGP0003i.png	sm-IMGP0003i.png	svadebnye	NULL	f	от 7 кг.	\N
192	Торт № 15 к.	IMGP0005.png	sm-IMGP0005.png	corporativnye	NULL	f	от 5 кг., 1900 руб/кг.	\N
193	Торт № 27 п.	IMGP0006.png	sm-IMGP0006.png	prazdnichnye	3D	f	от 3 кг 1900 руб/кг.	\N
194	Торт № 16 к.	IMGP0007.png	sm-IMGP0007.png	corporativnye	NULL	f	от 2,5 кг 1900 руб/кг.	\N
198	Торт № 33 с.	kiufvbtes.png	sm-kiufvbtes.png	svadebnye	NULL	f	от 3 кг 	\N
200	Торт № 34 с.	loiyfbnyewa.png	sm-loiyfbnyewa.png	svadebnye	NULL	f	от 5 кг.	\N
201	Торт № 15 д.	rtndewayui.png	sm-rtndewayui.png	detskie	NULL	f	от 3 кг.	\N
204	Торт № 28 п.	1708131.png	sm-1708131.png	prazdnichnye	risovannye	f	от 3 кг., 1900 руб/кг.	\N
208	Торт № 16 д.	aevctbntuivfgv.png	sm-aevctbntuivfgv.png	detskie	3D	f	от 3 кг	\N
209	Торт № 17 д.	asdasdhfjkljtyzf.png	sm-asdasdhfjkljtyzf.png	detskie	3D	f	от 3 кг 	\N
211	Торт № 29 п.	asdfgjkertyghjhj.png	sm-asdfgjkertyghjhj.png	prazdnichnye	3D	f	от 3,5 кг 2000 руб/кг.	\N
212	Торт № 35 с.	asdjkljhklasdfgh.png	sm-asdjkljhklasdfgh.png	svadebnye	lepka	f	от 2 кг	\N
213	Торт № 36 с.	asdjklzcvfh.png	sm-asdjklzcvfh.png	svadebnye	lepka	f	от 3 кг 	\N
214	Торт № 30 п.	cedtbtyvdzfhybht.png	sm-cedtbtyvdzfhybht.png	prazdnichnye	3D	t	Пряничный домик , размер и цена рассчитываются индивидуально.	\N
215	Торт № 31 п.	cevbtntyvdfvgnjh.png	sm-cevbtntyvdfvgnjh.png	prazdnichnye	3D	f	от 3 кг., 1900 руб/кг.	\N
221	Торт № 19 д.	ebymtgvdcetcrvet.png	sm-ebymtgvdcetcrvet.png	detskie	3D	f	от 3 кг.	\N
223	Торт № 32 п.	fasfgsljhb.png	sm-fasfgsljhb.png	prazdnichnye	2D	f	от 2 кг., 1400 руб/кг.	\N
224	Торт № 33 п.	fbyjcdfvtvczdbgu.png	sm-fbyjcdfvtvczdbgu.png	prazdnichnye	3D	t	от 3 кг., 2000 руб/кг	\N
225	Торт № 17 к .	fghjjhgfrnuuyyju.png	sm-fghjjhgfrnuuyyju.png	corporativnye	NULL	f	от 3 кг., 2000 руб/кг.	\N
230	Торт № 18 к 	kgjglkh.png	sm-kgjglkh.png	corporativnye	3D	f	от 15 кг., 1900 руб/кг	\N
231	Торт № 34 п.	kjgvczujkggsd.png	sm-kjgvczujkggsd.png	prazdnichnye	risovannye	f	от 2,5 кг., 1900 руб/кг.	\N
234	Торт № 35 п.	lkjhfdambjgtr.png	sm-lkjhfdambjgtr.png	prazdnichnye	yagody	f	от 3 кг., 1900 руб/кг.	\N
235	Торт № 36 п.	lkjljhfhfdalj.png	sm-lkjljhfhfdalj.png	prazdnichnye	2D	f	от 2 кг., 1800 руб/кг.	\N
236	Торт № 22 д.	mnvjfurthfb.png	sm-mnvjfurthfb.png	detskie	3D	t	от 3 кг	\N
237	Торт № 37 п.	nixerufgbviugbcidhhgdsfg.png	sm-nixerufgbviugbcidhhgdsfg.png	prazdnichnye	yagody	f	от 2,5 кг., 1900 руб/кг.	\N
239	Торт № 38 п.	sdfgghghjadfdgjk.png	sm-sdfgghghjadfdgjk.png	prazdnichnye	3D	f	от 2,5 кг., 2000 руб/кг.	\N
243	Торт № 39 п.	vzxhldhfuith.png	sm-vzxhldhfuith.png	prazdnichnye	3D	f	от 2,5 кг., 1900 руб/кг.	\N
244	Торт № 37 с.	xcasvbtrnugbrtfcthfgh.png	sm-xcasvbtrnugbrtfcthfgh.png	svadebnye	lepka	f	от 6 кг.	\N
246	Торт № 40 п.	1907131.png	sm-1907131.png	prazdnichnye	yagody	f	от 3,5 кг., 2200 руб/кг.	\N
247	Торт № 41 п.	cccccccdrnttgnhyj.png	sm-cccccccdrnttgnhyj.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг.	\N
248	Торт № 42 п.	ccwdfffghj.png	sm-ccwdfffghj.png	prazdnichnye	NULL	f	от 3 кг., 2000 руб/кг.	\N
249	Торт № 43 п.	cxercnyu.png	sm-cxercnyu.png	prazdnichnye	NULL	f	от 2 кг., 1900 руб/кг.	\N
250	Торт № 44 п.	ddddddddrtnjhugy.png	sm-ddddddddrtnjhugy.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг.	\N
253	Торт № 45 п.	ffffffbysrvtnyfgvsg.png	sm-ffffffbysrvtnyfgvsg.png	prazdnichnye	2D	f	от 1 кг., 1400 руб/кг.	\N
254	Торт № 46 п.	gnbryskuihg.png	sm-gnbryskuihg.png	prazdnichnye	NULL	f	от 2 кг., 1900 руб/кг.	\N
256	Торт № 47 п.	jhgfdytebhyugjukyfdrt.png	sm-jhgfdytebhyugjukyfdrt.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг.	\N
257	Торт № 19 к.	jjjjjjjkdsggj.png	sm-jjjjjjjkdsggj.png	corporativnye	NULL	f	от 2,5 кг., 1400 руб/кг.	\N
261	Торт № 23 д.	ksfghmkj.png	sm-ksfghmkj.png	detskie	3D	t	от 2 кг.	\N
263	Торт № 48 п.	mjybgrgfdx.png	sm-mjybgrgfdx.png	prazdnichnye	NULL	f	от 2,5 кг., 2000 руб/кг.	\N
265	Торт № 49 п.	qqqqqqqqqqqqqqgnjfgsdffffff.png	sm-qqqqqqqqqqqqqqgnjfgsdffffff.png	prazdnichnye	3D	f	от 2 кг, 1900 руб/кг.	\N
268	Торт № 50 п.	tttttttttttnmjevrtbynk.png	sm-tttttttttttnmjevrtbynk.png	prazdnichnye	NULL	f	от 3 кг., 2000 руб/кг.	\N
271	Торт № 51 п.	ddddddddshtggggggggggg.png	sm-ddddddddshtggggggggggg.png	prazdnichnye	NULL	f	от 3 кг., 2000 руб/кг.	\N
272	Торт № 25 д.	dddddddrrrrrrrrrrrrfggggggggrrrrrrrrr.png	sm-dddddddrrrrrrrrrrrrfggggggggrrrrrrrrr.png	detskie	NULL	f	от 3,5 кг.	\N
276	Торт № 52 п.	hhhhhhhhhyyyyyyyytttttttttttttttttttt.png	sm-hhhhhhhhhyyyyyyyytttttttttttttttttttt.png	prazdnichnye	NULL	t	от 3,5 кг., 2000 руб/кг.	\N
280	Торт № 53 п.	kkkkkkkkkkjhhhhhhhhhhhhh.png	sm-kkkkkkkkkkjhhhhhhhhhhhhh.png	prazdnichnye	NULL	f	от 4 кг., 2000 руб/кг.	\N
281	Торт № 54 п.	loinkuygbvykjjyguyesesees.png	sm-loinkuygbvykjjyguyesesees.png	prazdnichnye	NULL	f	от 2,5 кг., 2000 руб/кг.	\N
283	Торт № 55 п.	sssssssddddddddddffffffffgggggggggg.png	sm-sssssssddddddddddffffffffgggggggggg.png	prazdnichnye	NULL	f	от 3 кг 2000 руб/кг.	\N
286	Торт № 29 д.	xxxrrggyyyyyyyyyyyyyyyyyyy.png	sm-xxxrrggyyyyyyyyyyyyyyyyyyy.png	detskie	NULL	f	от 2 кг 	\N
403	Торт № 56 п.	250820131.png	sm-250820131.png	prazdnichnye	NULL	f	От 4 кг, 2000 руб кг.	\N
407	Торт № 31 д.	300813.png	sm-300813.png	detskie	NULL	f	От 2,5 кг.	\N
415	Торт № 32 д.	300820131.png	sm-300820131.png	detskie	NULL	f	От 2,5 кг.	\N
425	Торт № 20 к.	300720131.png	sm-300720131.png	corporativnye	NULL	f	от 4 кг., 2000 руб/кг.	\N
427	Торт № 21 к.	3007131.png	sm-3007131.png	corporativnye	NULL	f	от 4 кг., 2000 руб/кг.	\N
430	Торт № 38 с.	2908131.png	sm-2908131.png	svadebnye	NULL	f	от 2,5 кг	\N
432	Торт № 39 с.	010613.png	sm-010613.png	svadebnye	NULL	f	от 4 кг.	\N
433	Торт № 40 с.	0208131.png	sm-0208131.png	svadebnye	NULL	f	от 3 кг.	\N
441	Торт № 37 д.	020820131.png	sm-020820131.png	detskie	NULL	f	От 2,5 кг.	\N
442	Торт № 38 д.	0709131.png	sm-0709131.png	detskie	NULL	f	От 4 кг. 	\N
443	Торт № 39 д.	0807131.png	sm-0807131.png	detskie	NULL	f	От 3 кг.	\N
454	Торт № 57	070620131.png	sm-070620131.png	prazdnichnye	NULL	f	От 2,5 кг. 1900 руб/ кг.	\N
458	Торт № 22 к.	0809131.png	sm-0809131.png	corporativnye	NULL	f	от 3 кг., 1900 руб/кг.	\N
462	Торт № 58 п.	1006134.png	sm-1006134.png	prazdnichnye	NULL	f	От 2,5 кг,1900 руб кг.	\N
467	Торт № 59 п.	050720131.png	sm-050720131.png	prazdnichnye	NULL	f	От 2 кг,1600 руб кг.	\N
470	Торт № 42 д.	0306131.png	sm-0306131.png	detskie	NULL	f	От 3 кг. 	\N
471	Торт № 23 к.	1509131.png	sm-1509131.png	corporativnye	NULL	f	От 2 кг 1400 руб/ кг	\N
473	Торт № 24 к.	2706131.png	sm-2706131.png	corporativnye	NULL	f	от 3 кг., 1900 руб/кг.	\N
476	Торт № 43 д.	1006131.png	sm-1006131.png	detskie	NULL	f	от 3 кг.	\N
479	Торт № 41 с.	120920131.png	sm-120920131.png	svadebnye	NULL	f	от 5 кг.	\N
485	Торт № 60 п.	080920131.png	sm-080920131.png	prazdnichnye	NULL	f	от 3 кг., 2000 руб/кг.	\N
487	Торт № 61 п.	130720131.png	sm-130720131.png	prazdnichnye	NULL	f	от 2 кг., 1900 руб/кг.	\N
489	Торт № 62 п.	0906136.png	sm-0906136.png	prazdnichnye	NULL	f	от 2,5 кг., 2000 руб/кг.	\N
491	Торт № 63 п.	0908131.png	sm-0908131.png	prazdnichnye	NULL	f	от 2 кг 1900 руб/кг.	\N
496	Торт № 64 п.	1508131.png	sm-1508131.png	prazdnichnye	NULL	t	от 2,5 кг, 1900 руб/кг.	\N
497	Торт № 65 п.	1409132.png	sm-1409132.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг.	\N
500	Торт № 66 п.	0806131.png	sm-0806131.png	prazdnichnye	NULL	f	от 3 кг., 2000 руб/кг.	\N
502	Торт № 67 п.	1406131.png	sm-1406131.png	prazdnichnye	NULL	f	от 2,5 кг 1900 руб/кг.	\N
503	Торт № 68 п.	0906132.png	sm-0906132.png	prazdnichnye	NULL	f	от 2,5 кг 1900 руб/кг.	\N
506	Торт № 69 п.	0708131.png	sm-0708131.png	prazdnichnye	NULL	t	от 3 кг., 2000 руб/кг.	\N
518	Торт № 25 к.	0102141.png	sm-0102141.png	corporativnye	NULL	f	от 3 кг., 2000 руб/кг.	\N
521	Торт № 70 п.	0202141.png	sm-0202141.png	prazdnichnye	NULL	f	от 2,5 кг, 1900 руб/кг.	\N
524	Торт № 26 к.	0403141.png	sm-0403141.png	corporativnye	NULL	f	От 2 кг, 1700 руб/ кг.	\N
526	Торт № 27 к.	0611133.png	sm-0611133.png	corporativnye	NULL	f	От 3 кг, 1800 руб/ кг.	\N
527	Торт № 28 к.	0711131.png	sm-0711131.png	corporativnye	NULL	f	От 6 кг, 1900 руб/кг.	\N
536	Торт № 48 д.	0612131.png	sm-0612131.png	detskie	NULL	f	От 3 кг.	\N
556	Торт № 71 п.	0212132.png	sm-0212132.png	prazdnichnye	NULL	f	От 3 кг, 1900 руб кг.	\N
560	Торт № 72 п.	2012131.png	sm-2012131.png	prazdnichnye	NULL	f	От 4 кг ,1900 руб кг.	\N
563	Торт № 73 п.	2710131.png	sm-2710131.png	prazdnichnye	NULL	f	От 2 кг, 1900 руб кг.	\N
567	Торт № 74 п.	2911131.png	sm-2911131.png	prazdnichnye	NULL	f	От 3 кг, 2000 руб кг.	\N
570	Торт № 75 п.	291220131.png	sm-291220131.png	prazdnichnye	NULL	f	От 3 кг, 1900 руб кг.	\N
573	Торт № 42 с.	0401141.png	sm-0401141.png	svadebnye	NULL	f	От 7 кг	\N
574	Торт № 29 к.	03120131.png	sm-03120131.png	corporativnye	NULL	f	от 2,5 кг 1900 руб/кг.	\N
577	Торт № 30 к.	0110131.png	sm-0110131.png	corporativnye	NULL	f	от 2,5 кг., 1800 руб/кг.	\N
578	Торт № 31 к.	2711131.png	sm-2711131.png	corporativnye	NULL	f	от 4 кг., 1900 руб/кг.	\N
579	Торт № 32 к.	0512131.png	sm-0512131.png	corporativnye	NULL	f	от 2,5 кг., 1800руб/кг.	\N
588	Торт № 76 п.	181020131.png	sm-181020131.png	prazdnichnye	NULL	f	от 3 кг 1900 руб/кг.	\N
589	Торт № 77 п.	240120141.png	sm-240120141.png	prazdnichnye	NULL	f	От 3 кг,2000 руб кг.	\N
591	Торт № 78 п.	0611131.png	sm-0611131.png	prazdnichnye	NULL	f	От 3 кг, 2000 руб кг.	\N
592	Торт № 79 п.	3101141.png	sm-3101141.png	prazdnichnye	NULL	f	От 3 кг, 2000 руб кг.	\N
594	Торт № 80 п.	3012132.png	sm-3012132.png	prazdnichnye	NULL	f	От 3 кг , 2000 руб кг.	\N
609	Торт № 58 д.	1110131.png	sm-1110131.png	detskie	NULL	f	от 4 кг.	\N
615	Торт № 60 д.	1501141.png	sm-1501141.png	detskie	NULL	f	от 2,5 кг	\N
618	Торт № 61 д.	1310131.png	sm-1310131.png	detskie	NULL	f	от 2,5 кг.	\N
630	Торт № 81 п.	2002141.png	sm-2002141.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг.	\N
631	Торт № 82 п.	1411132.png	sm-1411132.png	prazdnichnye	NULL	f	От 3 кг, 2000 руб за кг.	\N
632	Торт № 83 п.	2502141.png	sm-2502141.png	prazdnichnye	NULL	f	От 3 кг, 1900 руб за кг.	\N
633	Торт № 84 п.	1601141.png	sm-1601141.png	prazdnichnye	NULL	f	От 4 кг , 1900 руб за кг.	\N
642	Торт № 64 д.	2202141.png	sm-2202141.png	detskie	NULL	f	От 2 кг. 	\N
660	Торт № 43 с.	1410131.png	sm-1410131.png	svadebnye	NULL	f	От 7 кг, 	\N
666	Торт № 85 п.	2302141.png	sm-2302141.png	prazdnichnye	NULL	f	От 2 кг ,1800 руб за кг.	\N
669	Торт № 86 п.	1712131.png	sm-1712131.png	prazdnichnye	NULL	f	от 2,5 кг 1900 руб за кг.	\N
672	Торт № 33 к.	2701141.png	sm-2701141.png	corporativnye	NULL	f	От 4 кг. 1900 руб/ кг\r\n	\N
675	Торт № 87 п.	1602141.png	sm-1602141.png	prazdnichnye	NULL	f	 от 3 кг., 1900 руб/кг	\N
679	Торт № 68 д.	050420153.png	sm-050420153.png	detskie	NULL	f	от 3 кг.	\N
685	Торт № 69 д.	070420152.png	sm-070420152.png	detskie	NULL	f	от 3 кг.	\N
691	Торт № 71 д.	11042015.png	sm-11042015.png	detskie	NULL	f	от 3 кг.	\N
697	Торт № 88 п.	120420152.png	sm-120420152.png	prazdnichnye	NULL	f	от 2,5 кг., 2000 руб/кг	\N
700	Торт № 89 п.	130420152.png	sm-130420152.png	prazdnichnye	NULL	f	от 3 кг., 2000 руб/кг	\N
712	Торт № 75 д.	170420152.png	sm-170420152.png	detskie	NULL	f	от 4 кг., 	\N
721	Торт № 77 д.	200420152.png	sm-200420152.png	detskie	NULL	f	от 2,5 кг.	\N
757	Торт № 34 к.	040320152.png	sm-040320152.png	corporativnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
760	Торт № 90 п.	020520152.png	sm-020520152.png	prazdnichnye	NULL	f	 от 10 кг., 1900 руб/кг	\N
763	Торт № 91 п .	030520152.png	sm-030520152.png	prazdnichnye	NULL	f	от 3 кг., 1900 руб/кг	\N
766	Торт № 92 п.	050520152.png	sm-050520152.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
777	Торт № 35 к.	070520152.png	sm-070520152.png	corporativnye	NULL	f	от 3 кг., 1900 руб/кг	\N
780	Торт № 36 к.	110520152.png	sm-110520152.png	corporativnye	NULL	f	от 3 кг., 1800 руб/кг	\N
783	Торт № 37 к.	100520152.png	sm-100520152.png	corporativnye	NULL	f	от 3 кг., 1900 руб/кг	\N
786	Торт № 38 к.	080520152.png	sm-080520152.png	corporativnye	NULL	f	от 3 кг., 1800 руб/кг	\N
789	Торт № 39 к.	160520152.png	sm-160520152.png	corporativnye	NULL	f	от 5 кг., 1900 руб/кг	\N
792	Торт № 40 к.	090520152.png	sm-090520152.png	corporativnye	NULL	f	от 3 кг., 1900 руб/кг	\N
795	Торт № 41 к.	120520152.png	sm-120520152.png	corporativnye	NULL	f	от 5 кг., 1900 руб/кг	\N
798	Торт № 94 п.	130520152.png	sm-130520152.png	prazdnichnye	NULL	f	от 3,5 кг., 1900 руб/кг	\N
801	Торт № 95 п.	140520152.png	sm-140520152.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
804	Торт № 96 п.	150520152.png	sm-150520152.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
807	Торт № 97 п.	210520152.png	sm-210520152.png	prazdnichnye	NULL	f	от 3 кг., 1900 руб/кг	\N
810	Торт № 98 п.	220520152.png	sm-220520152.png	prazdnichnye	NULL	f	от 3,5 кг., 1900 руб/кг	\N
813	Торт № 99 п.	200520152.png	sm-200520152.png	prazdnichnye	NULL	f	от 8 кг., 1900 руб/кг	\N
816	Торт № 100 п.	190520152.png	sm-190520152.png	prazdnichnye	NULL	f	от 2 кг., 1800 руб/кг	\N
819	Торт № 101 п.	230520152.png	sm-230520152.png	prazdnichnye	NULL	f	от 3,5 кг., 2200 руб/кг	\N
821	Торт № 102 п.	290520152.png	sm-290520152.png	prazdnichnye	NULL	f	от 3 кг., 2000 руб/кг	\N
825	Торт № 103 п.	300520152.png	sm-300520152.png	prazdnichnye	NULL	f	от 3 кг., 1900 руб/кг	\N
836	Торт № 86 д.	250520152.png	sm-250520152.png	detskie	NULL	f	от 2,5 кг	\N
840	Торт № 87 д.	270520152.png	sm-270520152.png	detskie	NULL	f	от 2,5 кг.	\N
855	Торт № 42 к.	020320152.png	sm-020320152.png	corporativnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
858	Торт № 104 п.	060320152.png	sm-060320152.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
861	Торт № 105 п.	030320152.png	sm-030320152.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
864	Торт № 106 п.	070320152.png	sm-070320152.png	prazdnichnye	NULL	f	от 3 кг., 2000 руб/кг	\N
867	Торт № 107 п.	090320152.png	sm-090320152.png	prazdnichnye	NULL	f	от 3 кг., 1900 руб/кг	\N
873	Торт № 108 п.	0403201521.png	sm-0403201521.png	prazdnichnye	NULL	f	от 3 кг., 1900 руб/кг	\N
876	Торт № 109 п.	050320152.png	sm-050320152.png	prazdnichnye	NULL	f	от 3 кг., 2000 руб/кг	\N
879	Торт № 44 с.	100320152.png	sm-100320152.png	svadebnye	NULL	f	от 8 кг.	\N
882	Торт № 110 п.	110320152.png	sm-110320152.png	prazdnichnye	NULL	f	от 3,5 кг., 2000 руб/кг	\N
885	Торт № 90 д.	120320152.png	sm-120320152.png	detskie	NULL	f	от 3 кг.	\N
888	Торт № 111 п.	130320151.png	sm-130320151.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
891	Торт № 112 п.	150320152.png	sm-150320152.png	prazdnichnye	NULL	f	от 3,5 кг., 1900 руб/кг	\N
894	Торт № 113 п.	160320152.png	sm-160320152.png	prazdnichnye	NULL	f	от 4 кг., 1900 руб/кг	\N
895	Торт № 45 с.	170320151.png	sm-170320151.png	svadebnye	NULL	f	От 2,5 кг	\N
896	Торт № 46 с.	17032015.png	sm-17032015.png	svadebnye	NULL	f	От 2,5 кг 	\N
897	Торт № 47 с.	170320152.png	sm-170320152.png	svadebnye	NULL	f	от 7,5 кг	\N
900	Торт № 48 с.	200320152.png	sm-200320152.png	svadebnye	NULL	f	от 7,5 кг	\N
903	Торт № 114 п.	210320152.png	sm-210320152.png	prazdnichnye	NULL	f	от 4 кг., 2000 руб/кг	\N
906	Торт № 115 п.	220320152.png	sm-220320152.png	prazdnichnye	NULL	f	от 3 кг., 2000 руб/кг	\N
909	Торт № 91 д.	230320152.png	sm-230320152.png	detskie	NULL	f	от 2,5 кг.	\N
915	Торт № 116 п.	240320152.png	sm-240320152.png	prazdnichnye	NULL	f	от 3,5 кг., 1900 руб/кг	\N
930	Торт № 93 д.	290320152.png	sm-290320152.png	detskie	NULL	f	от 2,5 кг	\N
942	Торт № 97 д.	010220151.png	sm-010220151.png	detskie	NULL	f	от 2,5 кг.	\N
948	Торт № 98 д.	030220152.png	sm-030220152.png	detskie	NULL	f	от 2,5 кг	\N
966	Торт № 117 п.	090220152.png	sm-090220152.png	prazdnichnye	NULL	f	от 3 кг., 1800 руб/кг	\N
969	Торт № 43 к.	100220152.png	sm-100220152.png	corporativnye	NULL	f	от 3 кг., 1800 руб/кг	\N
975	Торт № 118 п.	130220152.png	sm-130220152.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
978	Торт № 119 п.	1102201521.png	sm-1102201521.png	prazdnichnye	NULL	f	от 5 кг., 2000 руб/кг\r\nАренда подставки оплачивается отдельно.	\N
981	Торт № 101 д.	1302201520.png	sm-1302201520.png	detskie	NULL	f	от 3 кг.	\N
990	Торт № 120 п.	030620152.png	sm-030620152.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
993	Торт № 121 п.	040620152.png	sm-040620152.png	prazdnichnye	NULL	f	от 3 кг., 2000 руб/кг	\N
996	Торт № 122 п.	010620152.png	sm-010620152.png	prazdnichnye	NULL	f	от 2,5 кг., 2000 руб/кг	\N
999	Торт № 49 с.	080620152.png	sm-080620152.png	svadebnye	NULL	f	от 7,5 кг	\N
1002	Торт № 50 с.	070620152.png	sm-070620152.png	svadebnye	NULL	f	от 6 кг.	\N
1005	Торт № 123 п.	100620152.png	sm-100620152.png	prazdnichnye	NULL	f	от 4 кг., 1900 руб/кг	\N
1011	Торт № 51 с.	090620152.png	sm-090620152.png	svadebnye	NULL	f	от 4 кг	\N
1012	Торт № 102 д.	100620150.png	sm-100620150.png	detskie	NULL	f	от 2,5 кг.	\N
1014	Торт № 103 д.	1006201510.png	sm-1006201510.png	detskie	NULL	f	от 2,5 кг	\N
1017	Торт № 104 д.	110620152.png	sm-110620152.png	detskie	NULL	f	от 3 кг.	\N
1024	Торт № 107 д.	12062015.png	sm-12062015.png	detskie	NULL	f	от 2,5 кг.	\N
1029	Торт № 124 п.	140620152.png	sm-140620152.png	prazdnichnye	NULL	f	от 2,5 кг., 1800 руб/кг	\N
1032	Торт № 125 п.	150620152.png	sm-150620152.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
1035	Торт № 126 п.	160620152.png	sm-160620152.png	prazdnichnye	NULL	f	от 4 кг., 1900 руб/кг	\N
1038	Торт № 127 п.	170620152.png	sm-170620152.png	prazdnichnye	NULL	f	от 4 кг., 2000 руб/кг	\N
1041	Торт № 52 с.	180620152.png	sm-180620152.png	svadebnye	NULL	f	от 3,5 кг.	\N
1044	Торт № 128 п.	190620152.png	sm-190620152.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
1047	Торт № 53 с.	200620152.png	sm-200620152.png	svadebnye	NULL	f	от 7,5 кг	\N
1050	Торт № 108 д.	210620152.png	sm-210620152.png	detskie	NULL	f	от 2,5 кг.	\N
1053	Торт № 109 д.	220620151.png	sm-220620151.png	detskie	NULL	f	от 2,5 кг.	\N
1056	Торт № 110 д.	230620152.png	sm-230620152.png	detskie	NULL	f	от 2,5 кг.	\N
1062	Торт № 113 д.	230620155.png	sm-230620155.png	detskie	NULL	f	от 2,5 кг.	\N
1063	Торт № 129 п.	240620151.png	sm-240620151.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
1064	Торт № 130 п.	240620153.png	sm-240620153.png	prazdnichnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
1065	Торт № 131 п.	240620152.png	sm-240620152.png	prazdnichnye	NULL	f	от 2,5 кг., 2000 руб/кг	\N
1066	Торт № 44 к.	250620151.png	sm-250620151.png	corporativnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
1067	Торт № 45 к.	250620152.png	sm-250620152.png	corporativnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
1068	Торт № 46 к.	25062015.png	sm-25062015.png	corporativnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
1069	Торт № 47 к.	250620155.png	sm-250620155.png	corporativnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
1070	Торт № 48 к.	250620154.png	sm-250620154.png	corporativnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
1071	Торт № 49 к.	250620153.png	sm-250620153.png	corporativnye	NULL	f	от 2,5 кг., 1900 руб/кг	\N
1074	Торт № 114 д.	250620159.png	sm-250620159.png	detskie	NULL	f	от 	\N
1078	Торт № 132 п.	260620155.png	sm-260620155.png	prazdnichnye	NULL	f	капкейки от 220 руб/шт	\N
1079	Торт № 133 п.	260620153.png	sm-260620153.png	prazdnichnye	NULL	f	капкейки от 220 руб/шт	\N
1080	Торт № 134 п.	260620154.png	sm-260620154.png	prazdnichnye	NULL	f	капкейки от 220 руб/шт	\N
1083	Торт № 117 д.	260620157.png	sm-260620157.png	detskie	NULL	f	кейк попсы 	\N
1098	Торт № 118 д.	t-4.jpg	sm-t-4.jpg	detskie	\N	f	От 2 кг 	\N
1099	Торт № 119 д.	t-3.jpg	sm-t-3.jpg	detskie	\N	f	От 2 кг 	\N
1100	Торт № 120 д.	t-2.jpg	sm-t-2.jpg	detskie	\N	f	От 2,5 кг 	\N
1101	Торт № 121 д.	t-1.jpg	sm-t-1.jpg	detskie	\N	f	От 2,5 кг 	\N
1103	Торт N 122 д.	IMG_20181203_193827.jpg	sm-IMG_20181203_193827.jpg	detskie	\N	f	От 2,5 кг 	\N
1105	Торт N 124 д.	IMG_20181203_200820.jpg	sm-IMG_20181203_200820.jpg	detskie	\N	f	От 2 кг 	\N
1115	Торт N 127 д.	IMG_20181203_231928.jpg	sm-IMG_20181203_231928.jpg	detskie	\N	f	От 2,5 кг	\N
1119	Торт N 129 д.	IMG_20181203_232545.jpg	sm-IMG_20181203_232545.jpg	detskie	\N	f	От 2,5 кг 	\N
1123	Торт N 130 д.	IMG_20181203_233313.jpg	sm-IMG_20181203_233313.jpg	detskie	\N	f	От 2 кг 	\N
1124	Торт N 131 д.	IMG_20181203_233735.jpg	sm-IMG_20181203_233735.jpg	detskie	\N	f	От 2,5 кг	\N
1126	Торт N 133 д	IMG_20181203_234036.jpg	sm-IMG_20181203_234036.jpg	detskie	\N	f	От 3,5 кг 	\N
1130	Торт N 134 д.	IMG_20181203_234628.jpg	sm-IMG_20181203_234628.jpg	detskie	\N	f	От 2,5 кг 	\N
1136	Торт N 136 д.	IMG_20181203_235444.jpg	sm-IMG_20181203_235444.jpg	detskie	\N	f	От 3 кг	\N
1137	Торт N 137 д.	IMG_20181203_235601.jpg	sm-IMG_20181203_235601.jpg	detskie	\N	f	От 2 кг	\N
1138	Фото N 138 д.	IMG_20181203_235756.jpg	sm-IMG_20181203_235756.jpg	detskie	\N	f	Кейк попсы 	\N
1139	Торт N 139 д.	IMG_20181203_235944.jpg	sm-IMG_20181203_235944.jpg	detskie	\N	f	От 2 кг 	\N
1141	Торт N 141 д.	IMG_20181204_000243.jpg	sm-IMG_20181204_000243.jpg	detskie	\N	f	От 2,5 кг	\N
1143	Торт N 142 д.	IMG_20181204_000501.jpg	sm-IMG_20181204_000501.jpg	detskie	\N	f	От 2 кг 	\N
1147	Торт N 144 д.	IMG_20181204_001121.jpg	sm-IMG_20181204_001121.jpg	detskie	\N	f	От 3 кг 	\N
1154	Торт N 147 д.	IMG_20181206_220355.jpg	sm-IMG_20181206_220355.jpg	detskie	\N	f	От 2 кг	\N
1157	Фото N 148 д.	IMG_20181206_220837.jpg	sm-IMG_20181206_220837.jpg	detskie	\N	f	Печенье 	\N
1159	Торт N 149 д.	IMG_20181206_221301.jpg	sm-IMG_20181206_221301.jpg	detskie	\N	f	От 2 кг 	\N
1160	Торт N 135 п.	IMG_20181206_221324.jpg	sm-IMG_20181206_221324.jpg	prazdnichnye	\N	f	От 2 кг 1800 руб/кг	\N
1162	Торт N 150 д.	IMG_20181206_221806.jpg	sm-IMG_20181206_221806.jpg	detskie	\N	f	От 5 кг 	\N
1164	Фото N 151 д.	IMG_20181206_222233.jpg	sm-IMG_20181206_222233.jpg	detskie	\N	f	Капкейки 	\N
1165	Торт N 152 д.	IMG_20181206_222259.jpg	sm-IMG_20181206_222259.jpg	detskie	\N	f	От 2 кг	\N
1168	Торт N 153 д.	IMG_20181206_222447.jpg	sm-IMG_20181206_222447.jpg	detskie	\N	f	От4 кг 	\N
1170	Торт N 154 д.	IMG_20181206_223815.jpg	sm-IMG_20181206_223815.jpg	detskie	\N	f	От 2 кг 	\N
1171	Фото N 155 д.	IMG_20181206_223833.jpg	sm-IMG_20181206_223833.jpg	detskie	\N	f	Капкейки 	\N
1172	Фото N 156 д.	IMG_20181206_223848.jpg	sm-IMG_20181206_223848.jpg	detskie	\N	f	Капкейки 	\N
1173	Торт N 157 д.	IMG_20181206_223924.jpg	sm-IMG_20181206_223924.jpg	detskie	\N	f	От 1,5 кг 	\N
1177	Торт N 160 д.	IMG_20181206_224807.jpg	sm-IMG_20181206_224807.jpg	detskie	\N	f	От 2 кг	\N
1178	Фото N 161 д.	IMG_20181206_224839.jpg	sm-IMG_20181206_224839.jpg	detskie	\N	f	Капкейки 	\N
1180	Торт N 162 д.	IMG_20181206_224926.jpg	sm-IMG_20181206_224926.jpg	detskie	\N	f	От 2,5 кг	\N
1182	Торт N 163 д.	IMG_20181206_225008.jpg	sm-IMG_20181206_225008.jpg	detskie	\N	f	Торт от 3 кг 	\N
1184	Торт N 164 д.	IMG_20181206_225726.jpg	sm-IMG_20181206_225726.jpg	detskie	\N	f	Торт от 2 кг	\N
1185	Торт N 165 д.	IMG_20181206_225744.jpg	sm-IMG_20181206_225744.jpg	detskie	\N	f	От 2 кг	\N
1186	Торт N 166 д.	IMG_20181206_225817.jpg	sm-IMG_20181206_225817.jpg	detskie	\N	f	От 2,5 кг 	\N
1188	Торт N 168 д.	IMG_20181206_225852.jpg	sm-IMG_20181206_225852.jpg	detskie	\N	f	От 2 кг	\N
1199	Торт N 136 п.	IMG_20181210_225740.jpg	sm-IMG_20181210_225740.jpg	prazdnichnye	\N	f	От 2,5 кг 1900 руб/кг	\N
1205	Торт N 171 д	IMG_20181210_231336.jpg	sm-IMG_20181210_231336.jpg	detskie	\N	f	От 2 кг	\N
1209	Торт N 173 д.	IMG_20181210_231150.jpg	sm-IMG_20181210_231150.jpg	detskie	\N	f	От 3,5 кг 	\N
1212	Торт N 174 д.	IMG_20181210_230952.jpg	sm-IMG_20181210_230952.jpg	detskie	\N	f	От 2,5 кг 	\N
1213	Торт N 175 д.	IMG_20181210_230922.jpg	sm-IMG_20181210_230922.jpg	detskie	\N	f	От 3 кг 	\N
1214	Фото N 176 д.	IMG_20181210_230902.jpg	sm-IMG_20181210_230902.jpg	detskie	\N	f	Капкейки 	\N
1215	Торт N 177 д.	IMG_20181210_230836.jpg	sm-IMG_20181210_230836.jpg	detskie	\N	f	От 2кг 	\N
1216	Торт N 178 д 	IMG_20181210_230819.jpg	sm-IMG_20181210_230819.jpg	detskie	\N	f	От 3 кг	\N
1217	Фото N 179 д.	IMG_20181210_230739.jpg	sm-IMG_20181210_230739.jpg	detskie	\N	f	Кейк попсы	\N
1218	Фото N 180 д.	IMG_20181210_230721.jpg	sm-IMG_20181210_230721.jpg	detskie	\N	f	Кейк попсы	\N
1220	Торт N 182 д.	IMG_20181210_230618.jpg	sm-IMG_20181210_230618.jpg	detskie	\N	f	От 2 кг 	\N
1221	Торт N 183 д.	IMG_20181210_235044.jpg	sm-IMG_20181210_235044.jpg	detskie	\N	f	От 2,5 кг 	\N
1222	Торт N 184 д.	IMG_20181210_235103.jpg	sm-IMG_20181210_235103.jpg	detskie	\N	f	От 3 кг	\N
1223	Торт N 185 д.	IMG_20181210_235121.jpg	sm-IMG_20181210_235121.jpg	detskie	\N	f	От 2,5 кг	\N
1224	Торт N 186 д.	IMG_20181210_235140.jpg	sm-IMG_20181210_235140.jpg	detskie	\N	f	От 2 кг	\N
1226	Фото N 187 д.	IMG_20181217_175804.jpg	sm-IMG_20181217_175804.jpg	detskie	\N	f	Капкейки 	\N
1227	Торт N 188 д.	IMG_20181217_180045.jpg	sm-IMG_20181217_180045.jpg	detskie	\N	f	От 2,5 кг	\N
1228	Торт N 137 п.	IMG_20181217_180316.jpg	sm-IMG_20181217_180316.jpg	prazdnichnye	\N	f	От 2,5 кг 1900 руб/кг	\N
1229	Торт N 138 п.	IMG_20181217_180349.jpg	sm-IMG_20181217_180349.jpg	prazdnichnye	\N	f	От 3 кг 1900 руб/кг	\N
1230	Торт N 139 п.	IMG_20181217_180414.jpg	sm-IMG_20181217_180414.jpg	prazdnichnye	\N	f	От 2 кг 1700 руб/кг	\N
1231	Торт N 140 п.	IMG_20181217_180430.jpg	sm-IMG_20181217_180430.jpg	prazdnichnye	\N	f	От 2,5 кг 1900 руб/кг	\N
1232	Торт N 141 п.	IMG_20181217_180452.jpg	sm-IMG_20181217_180452.jpg	prazdnichnye	\N	f	От 2,5 кг 1900 руб/кг	\N
1233	Торт N 142 п.	IMG_20181217_181024.jpg	sm-IMG_20181217_181024.jpg	prazdnichnye	\N	f	От 2,5 кг 1900 руб/кг	\N
1234	Торт N 143 п.	IMG_20181217_181055.jpg	sm-IMG_20181217_181055.jpg	prazdnichnye	\N	f	От 1,5 кг 1400 руб/кг	\N
1235	Торт N 144 п.	IMG_20181217_181123.jpg	sm-IMG_20181217_181123.jpg	prazdnichnye	\N	f	От 1,5 кг 1400 руб/кг	\N
1236	Торт N 145 п.	IMG_20181217_181202.jpg	sm-IMG_20181217_181202.jpg	prazdnichnye	\N	f	От 1,5 кг 1400 руб/кг	\N
1237	Торт N 146 п.	IMG_20181217_181323.jpg	sm-IMG_20181217_181323.jpg	prazdnichnye	\N	f	От 2 кг 1900 руб/кг	\N
1238	Торт N 147 п.	IMG_20181217_181413.jpg	sm-IMG_20181217_181413.jpg	prazdnichnye	\N	f	От 2 кг 1800 руб/кг	\N
1239	Торт N 148 п.	IMG_20181217_181451.jpg	sm-IMG_20181217_181451.jpg	prazdnichnye	\N	f	От 4 кг 1900 руб/кг	\N
1240	Торт N 149 п.	IMG_20181217_181511.jpg	sm-IMG_20181217_181511.jpg	prazdnichnye	\N	f	От 2 кг 1900 руб/кг	\N
1241	Торт N 150 п.	IMG_20181217_181541.jpg	sm-IMG_20181217_181541.jpg	prazdnichnye	\N	f	От 2 кг 2000 руб/кг	\N
1242	Торт N 151 п.	IMG_20181217_181600.jpg	sm-IMG_20181217_181600.jpg	prazdnichnye	\N	f	От 1,5 кг 1400 руб/кг	\N
1243	Торт N 152 п.	IMG_20181217_181639.jpg	sm-IMG_20181217_181639.jpg	prazdnichnye	\N	f	От 3 кг 1900 руб/кг	\N
1245	Торт N 154 п.	IMG_20181217_182709.jpg	sm-IMG_20181217_182709.jpg	prazdnichnye	\N	f	От 1,5 кг 1900 руб/кг	\N
1246	Торт N 155 п.	IMG_20181217_182748.jpg	sm-IMG_20181217_182748.jpg	prazdnichnye	\N	f	От 3 кг 1900 руб/кг	\N
1247	Торт N 189 д.	IMG_20230214_161709.jpg	sm-IMG_20230214_161709.jpg	detskie	\N	f	От 2 кг 	\N
1248	Торт N 190 д.	IMG_20230214_154216.jpg	sm-IMG_20230214_154216.jpg	detskie	\N	f	От 2 кг	\N
1249	Торт N 191 д.	IMG_20230215_140840.jpg	sm-IMG_20230215_140840.jpg	detskie	\N	f	От 2 кг	\N
1250	Торт N 192 д.	IMG_20230210_192711_219.jpg	sm-IMG_20230210_192711_219.jpg	detskie	\N	f	От 2 кг	\N
1253	Торт N 194 д.	IMG_20230215_140701.jpg	sm-IMG_20230215_140701.jpg	detskie	\N	f	От 2,5 кг	\N
1254	Торт N 195 д.	IMG_20230214_153638.jpg	sm-IMG_20230214_153638.jpg	detskie	\N	f	От 2 кг	\N
1256	Торт N 156 п.	IMG_20230214_154119.jpg	sm-IMG_20230214_154119.jpg	prazdnichnye	\N	f	От 2 кг, 1900 руб/кг.	\N
1257	Торт N 157 п.	IMG_20230214_154020.jpg	sm-IMG_20230214_154020.jpg	prazdnichnye	\N	f	Бенто торт 400-500г.\r\n1300 руб/шт.\r\n1 свечка, 1 ложка.\r\n	\N
1258	Торт  N 158 п.	IMG_20230214_153351.jpg	sm-IMG_20230214_153351.jpg	prazdnichnye	\N	f	От 2,5 кг,2000 руб/ кг.	\N
1259	Торт N 159 п.	IMG_20230214_152800.jpg	sm-IMG_20230214_152800.jpg	prazdnichnye	\N	f	Бенто торт 400-500г.\r\n1300 руб/шт.\r\n1 свечка, 1 ложка.	\N
1260	Торт N 54 с.	IMG_20230214_153801.jpg	sm-IMG_20230214_153801.jpg	svadebnye	\N	f	От 2 кг,	\N
1261	Торт N 160 п.	IMG_20230214_162455.jpg	sm-IMG_20230214_162455.jpg	prazdnichnye	\N	f	От 2,5 кг, 1900 руб/кг.\r\n	\N
1262	Торт N 161 п.	IMG_20230214_162342.jpg	sm-IMG_20230214_162342.jpg	prazdnichnye	\N	f	Торт от 2 кг, 1700 руб/кг.\r\nКапкейки от 6 шт, 200 руб/ шт \r\n	\N
1263	Торт N 50 к.	IMG_20230214_162253.jpg	sm-IMG_20230214_162253.jpg	corporativnye	\N	f	От 2,5 кг, 1900 руб/ кг.	\N
1264	Торт N 197 д.	IMG_20230215_135517.jpg	sm-IMG_20230215_135517.jpg	detskie	\N	f	От 2 кг	\N
1265	Торт N 161 п 	IMG_20230214_162010.jpg	sm-IMG_20230214_162010.jpg	prazdnichnye	\N	f	От 1,5 кг, 1600 руб/ кг	\N
1266	Торт N 162 п.	IMG_20230215_135958.jpg	sm-IMG_20230215_135958.jpg	prazdnichnye	\N	f	От 1 кг, 1400 руб/кг.	\N
1267	Торт N 163 п.	IMG_20230215_140104.jpg	sm-IMG_20230215_140104.jpg	prazdnichnye	\N	f	От 1 кг , 1400 руб/кг.	\N
1268	Торт N 164 с 	IMG_20230215_140021.jpg	sm-IMG_20230215_140021.jpg	prazdnichnye	\N	f	От 1 кг, 1400 руб/кг.	\N
1269	Торт N 165 с 	IMG_20230214_161520.jpg	sm-IMG_20230214_161520.jpg	prazdnichnye	\N	f	От 1,5 кг, 1500 руб/кг.	\N
1270	Торт N 166 п.	IMG_20230214_161810.jpg	sm-IMG_20230214_161810.jpg	prazdnichnye	\N	f	Бенто торт 400-500 г.1300 руб/шт\r\n1 свечка\r\n1 ложка.	\N
1271	Торт N 167 п.	IMG_20230215_152137.jpg	sm-IMG_20230215_152137.jpg	prazdnichnye	\N	f	От 1 кг, 1600 руб/кг.	\N
1272	Торт N 168 п.	IMG_20230215_152039.jpg	sm-IMG_20230215_152039.jpg	prazdnichnye	\N	f	Капкейки 220 руб/шт.	\N
1274	Торт N 199 д.	IMG_20230215_151729.jpg	sm-IMG_20230215_151729.jpg	detskie	\N	f	От 2,5 кг	\N
1275	Торт N 200 д.	IMG_20230215_151616.jpg	sm-IMG_20230215_151616.jpg	detskie	\N	f	От 2 кг	\N
1276	Торт N 201 д.	IMG_20230215_151500.jpg	sm-IMG_20230215_151500.jpg	detskie	\N	f	От 1,5 кг	\N
1277	Торт N 202 д.	IMG_20230215_150414.jpg	sm-IMG_20230215_150414.jpg	detskie	\N	f	От 3 кг	\N
1278	Торт N 169 п.	IMG_20230215_151832.jpg	sm-IMG_20230215_151832.jpg	prazdnichnye	\N	f	Капкейки 220 руб/шт.	\N
1280	Торт N 171 п.	IMG_20230215_150823.jpg	sm-IMG_20230215_150823.jpg	prazdnichnye	\N	f	От 1 кг, 1600 руб/кг.	\N
1281	Торт N 172	IMG_20230215_150717.jpg	sm-IMG_20230215_150717.jpg	prazdnichnye	\N	f	От 2 кг, 1900 руб/кг.	\N
1282	Торт N 173	IMG_20230215_150610.jpg	sm-IMG_20230215_150610.jpg	prazdnichnye	\N	f	От 2,5 кг, 2000 руб/кг.\r\nТоппер оплачивается отдельно.	\N
1283	Торт N 51 к.	IMG_20230215_151032.jpg	sm-IMG_20230215_151032.jpg	corporativnye	\N	f	От 2 кг, 1700 руб/кг 	\N
1284	Торт N 203 д.	IMG_20230215_160337.jpg	sm-IMG_20230215_160337.jpg	detskie	\N	f	От 2,5 кг	\N
1285	Торт N 204 д.	IMG_20230215_160255.jpg	sm-IMG_20230215_160255.jpg	detskie	\N	f	От 2,5 кг 	\N
1286	Торт N 205 д.	IMG_20230215_185153.jpg	sm-IMG_20230215_185153.jpg	detskie	\N	f	От 2 кг	\N
1287	Торт N 206 д.	IMG_20230215_155931.jpg	sm-IMG_20230215_155931.jpg	detskie	\N	f	От1,5 кг	\N
1288	Торт N 207 д.	IMG_20230215_160119.jpg	sm-IMG_20230215_160119.jpg	detskie	\N	f	Капкейки 	\N
1289	Торт N 208 д.	IMG_20230215_160023.jpg	sm-IMG_20230215_160023.jpg	detskie	\N	f	Пирожное эскимо	\N
1290	Торт N 209 д.	IMG_20230215_155844.jpg	sm-IMG_20230215_155844.jpg	detskie	\N	f	От 2, 5 кг 	\N
1291	Торт N 210 д.	IMG_20230215_155754.jpg	sm-IMG_20230215_155754.jpg	detskie	\N	f	От 2,5 кг	\N
1292	Торт N 211 д.	IMG_20230215_155646.jpg	sm-IMG_20230215_155646.jpg	detskie	\N	f	От 2 кг	\N
1293	Торт N 212 д.	IMG_20230215_155424.jpg	sm-IMG_20230215_155424.jpg	detskie	\N	f	От 2,5 кг	\N
1295	Торт N 214 д.	IMG_20230215_155102.jpg	sm-IMG_20230215_155102.jpg	detskie	\N	f	От2,5 кг	\N
1296	Торт N 215 д.	IMG_20230215_155000.jpg	sm-IMG_20230215_155000.jpg	detskie	\N	f	От 2 кг	\N
1297	Торт N 216 д.	IMG_20230215_154805.jpg	sm-IMG_20230215_154805.jpg	detskie	\N	f	От 2 кг	\N
1298	Торт N 217 д.	IMG_20230215_154600.jpg	sm-IMG_20230215_154600.jpg	detskie	\N	f	От 2,5 кг	\N
1299	Торт N 218 д.	IMG_20230215_154502.jpg	sm-IMG_20230215_154502.jpg	detskie	\N	f	От 2 кг	\N
1300	Торт N 174 п.	IMG_20230215_160525.jpg	sm-IMG_20230215_160525.jpg	prazdnichnye	\N	f	От 2 кг, 1900 руб/кг.	\N
1301	Торт N 175 п.	IMG_20230215_160429.jpg	sm-IMG_20230215_160429.jpg	prazdnichnye	\N	f	От 3 кг, 2000 руб/кг.	\N
1302	Торт N 176 п.	IMG_20230215_155236.jpg	sm-IMG_20230215_155236.jpg	prazdnichnye	\N	f	От 2 кг, 1900 руб/кг.	\N
1303	Торт N 177 п.	IMG_20230215_154909.jpg	sm-IMG_20230215_154909.jpg	prazdnichnye	\N	f	Пирожное эскимо, 250 руб/шт.	\N
1304	Торт N 178 п.	IMG_20230215_154710.jpg	sm-IMG_20230215_154710.jpg	prazdnichnye	\N	f	От 3 кг, 1900 руб/кг.	\N
1305	Торт N 179 п.	IMG_20230215_154342.jpg	sm-IMG_20230215_154342.jpg	prazdnichnye	\N	f	От 2,5 кг, 1900 руб/кг.	\N
1306	Торт N 180 п.	IMG_20230215_154253.jpg	sm-IMG_20230215_154253.jpg	prazdnichnye	\N	f	От 2,5 кг, 2100 руб/кг.	\N
1307	Торт N 181 п.	IMG_20230215_154159.jpg	sm-IMG_20230215_154159.jpg	prazdnichnye	\N	f	От 3 кг, 1900 руб/кг.	\N
1308	Торт N 55 с.	IMG_20230215_155604.jpg	sm-IMG_20230215_155604.jpg	svadebnye	\N	f	От 2 кг	\N
1309	Торт N 219 д.	IMG_20230215_170028.jpg	sm-IMG_20230215_170028.jpg	detskie	\N	f	От 2 кг 	\N
1311	Торт N 221 д.	IMG_20230215_164502.jpg	sm-IMG_20230215_164502.jpg	detskie	\N	f	От 2 кг	\N
1312	Торт N 222 д.	IMG_20230215_164337.jpg	sm-IMG_20230215_164337.jpg	detskie	\N	f	От 4 кг	\N
1313	Торт N 182 п.	IMG_20230215_164039.jpg	sm-IMG_20230215_164039.jpg	prazdnichnye	\N	f	От 3,5 кг, 1800 руб/кг.	\N
1314	Торт N 183 п.	IMG_20230215_164150.jpg	sm-IMG_20230215_164150.jpg	prazdnichnye	\N	f	Пирожное эскимо,250 руб/ шт.	\N
1315	Торт N 184 п.	IMG_20230215_170353.jpg	sm-IMG_20230215_170353.jpg	prazdnichnye	\N	f	От 1 кг, 1400 руб/кг.	\N
1316	Торт N 185 п.	IMG_20230215_170246.jpg	sm-IMG_20230215_170246.jpg	prazdnichnye	\N	f	Кейкпопс 180 руб/шт.	\N
1317	Торт N 186 п.	IMG_20230215_170207.jpg	sm-IMG_20230215_170207.jpg	prazdnichnye	\N	f	От 3 кг, 1900 руб/кг.	\N
1318	Торт N 187 п.	IMG_20230215_170121.jpg	sm-IMG_20230215_170121.jpg	prazdnichnye	\N	f	От 3 кг	\N
1319	Торт N 188 п.	IMG_20230215_165939.jpg	sm-IMG_20230215_165939.jpg	prazdnichnye	\N	f	Цена договорная.	\N
1320	Торт N 189 п 	IMG_20230215_165838.jpg	sm-IMG_20230215_165838.jpg	prazdnichnye	\N	f	От 3 кг , 1900 руб/кг.	\N
1321	Торт N 190 п.	IMG_20230215_165747.jpg	sm-IMG_20230215_165747.jpg	prazdnichnye	\N	f	От 2 кг, 1900 руб/кг.	\N
1322	Торт N 191 п.	IMG_20230215_165703.jpg	sm-IMG_20230215_165703.jpg	prazdnichnye	\N	f	От 2 кг, 1900 руб/кг.	\N
1323	Торт N 192 п.	IMG_20230215_165623.jpg	sm-IMG_20230215_165623.jpg	prazdnichnye	\N	f	От 1,5 кг,1700 руб/кг.	\N
1324	Торт N 193 п.	IMG_20230215_165538.jpg	sm-IMG_20230215_165538.jpg	prazdnichnye	\N	f	От 2 кг,1900 руб/кг.	\N
1325	Торт N 194 п.	IMG_20230215_165459.jpg	sm-IMG_20230215_165459.jpg	prazdnichnye	\N	f	От 2 кг, 1900 руб/кг.	\N
1326	Торт N 195 п 	IMG_20230215_165103.jpg	sm-IMG_20230215_165103.jpg	prazdnichnye	\N	f	От 2 кг,1900 руб/кг.	\N
1327	Торт N 196 п.	IMG_20230215_164933.jpg	sm-IMG_20230215_164933.jpg	prazdnichnye	\N	f	От 2 кг,1900 руб/кг\r\n	\N
1328	Торт N 197 п.	IMG_20230215_164834.jpg	sm-IMG_20230215_164834.jpg	prazdnichnye	\N	f	От 2 кг, 1800 руб/кг.	\N
1329	Торт N 198 п.	IMG_20230215_164742.jpg	sm-IMG_20230215_164742.jpg	prazdnichnye	\N	f	Пряник тыква, 250 руб/шт.\r\nКейкпопс 180 руб/шт.	\N
1330	Торт N 199 п.	IMG_20230215_164656.jpg	sm-IMG_20230215_164656.jpg	prazdnichnye	\N	f	От 2 кг , 1800 руб/кг.	\N
1331	Торт N 200 п .	IMG_20230215_164608.jpg	sm-IMG_20230215_164608.jpg	prazdnichnye	\N	f	 От 2 кг, 1900 руб/кг.	\N
1332	Торт N 56 с.	IMG_20230215_165153.jpg	sm-IMG_20230215_165153.jpg	svadebnye	\N	f	От 5 кг,	\N
1333	Торт N 57 с.	IMG_20230215_164417.jpg	sm-IMG_20230215_164417.jpg	svadebnye	\N	f	От 2 кг, 	\N
1334	Торт N 223 д.	IMG_20230215_185813.jpg	sm-IMG_20230215_185813.jpg	detskie	\N	f	От 2 кг	\N
1335	Торт N 224 д.	IMG_20230215_185413.jpg	sm-IMG_20230215_185413.jpg	detskie	\N	f	От 3 кг	\N
1336	Торт N 225 д.	IMG_20230215_185334.jpg	sm-IMG_20230215_185334.jpg	detskie	\N	f	От 3,5 кг	\N
1337	Торт N 226 д.	IMG_20230215_185113.jpg	sm-IMG_20230215_185113.jpg	detskie	\N	f	От 2,5 кг	\N
1338	Торт N 227 д.	IMG_20230215_185037.jpg	sm-IMG_20230215_185037.jpg	detskie	\N	f	От 2 кг 	\N
1339	Торт N 228 д.	IMG_20230215_184914.jpg	sm-IMG_20230215_184914.jpg	detskie	\N	f	От 2 кг	\N
1341	Торт N 230 д.	IMG_20230215_184323.jpg	sm-IMG_20230215_184323.jpg	detskie	\N	f	От 2,5 кг	\N
1342	Торт N 231 д.	IMG_20230215_184345.jpg	sm-IMG_20230215_184345.jpg	detskie	\N	f	Кейкпопс 	\N
1343	Торт N 232 д.	IMG_20230215_183333.jpg	sm-IMG_20230215_183333.jpg	detskie	\N	f	От 2 кг	\N
1344	Торт N 233 д.	IMG_20230215_182811.jpg	sm-IMG_20230215_182811.jpg	detskie	\N	f	От 3 кг	\N
1345	Торт N 234 д.	IMG_20230215_182632.jpg	sm-IMG_20230215_182632.jpg	detskie	\N	f	От 2 кг	\N
1346	Торт N 201 п 	IMG_20230215_182722.jpg	sm-IMG_20230215_182722.jpg	prazdnichnye	\N	f	От 3,5 кг, 1800 руб/кг.	\N
1347	Торт N 202 	IMG_20230215_185730.jpg	sm-IMG_20230215_185730.jpg	prazdnichnye	\N	f	От 3 кг, 2000 руб/кг 	\N
1348	Торт N 203 п.	IMG_20230215_185640.jpg	sm-IMG_20230215_185640.jpg	prazdnichnye	\N	f	От 2,5 кг,1800 руб/кг.	\N
1349	Торт N 204 п.	IMG_20230215_185523.jpg	sm-IMG_20230215_185523.jpg	prazdnichnye	\N	f	Бенто торт 400-500 го,1300 руб/шт.\r\n1 ложка\r\n1 свечка	\N
1350	Торт N 205 п.	IMG_20230215_185451.jpg	sm-IMG_20230215_185451.jpg	prazdnichnye	\N	f	От 3 кг, 1900 руб/кг.	\N
1351	Торт N 206 п.	IMG_20230215_185230.jpg	sm-IMG_20230215_185230.jpg	prazdnichnye	\N	f	От 2 кг, 1900 руб/кг.	\N
1352	Торт N 207 п.	IMG_20230215_184951.jpg	sm-IMG_20230215_184951.jpg	prazdnichnye	\N	f	От 3 кг	\N
1353	Торт N 208 п.	IMG_20230215_184605.jpg	sm-IMG_20230215_184605.jpg	prazdnichnye	\N	f	От 1  кг \r\n	\N
1355	Торт N 210 п.	IMG_20230215_184433.jpg	sm-IMG_20230215_184433.jpg	prazdnichnye	\N	f	От 3 кг	\N
1356	Торт N 211п.	IMG_20230215_184416.jpg	sm-IMG_20230215_184416.jpg	prazdnichnye	\N	f	От 2 кг	\N
1357	Торт N 212 п.	IMG_20230215_184242.jpg	sm-IMG_20230215_184242.jpg	prazdnichnye	\N	f	От 2,5 кг	\N
1358	Торт N 213 п.	IMG_20230215_183217.jpg	sm-IMG_20230215_183217.jpg	prazdnichnye	\N	f	Бенто торт 400-500г.\r\n	\N
1359	Торт N 214 п	IMG_20230215_183118.jpg	sm-IMG_20230215_183118.jpg	prazdnichnye	\N	f	Имбирные пряники\r\n	\N
1360	Торт N 215 п.	IMG_20241211_120035.jpg	sm-IMG_20241211_120035.jpg	prazdnichnye	\N	f	От 3,5 кг	\N
1361	Торт N 216 п.	IMG_20230216_094741.jpg	sm-IMG_20230216_094741.jpg	prazdnichnye	\N	f	От 2 кг	\N
1362	Торт N 52 к.	IMG_20230216_094938.jpg	sm-IMG_20230216_094938.jpg	corporativnye	\N	f	От 3 кг,1900 руб/кг.	\N
1364	Торт N 236 д.	IMG_20230216_103950.jpg	sm-IMG_20230216_103950.jpg	detskie	\N	f	От 3,5 кг	\N
1365	Торт N 237 д.	IMG_20230216_103848.jpg	sm-IMG_20230216_103848.jpg	detskie	\N	f	От 2,5 кг	\N
1366	Торт N 238 д.	IMG_20230216_103726.jpg	sm-IMG_20230216_103726.jpg	detskie	\N	f	От 2 кг	\N
1367	Торт N 239 д.	IMG_20230216_101653.jpg	sm-IMG_20230216_101653.jpg	detskie	\N	f	Капкейки 	\N
1368	Торт N 53 к.	IMG_20230216_101557.jpg	sm-IMG_20230216_101557.jpg	corporativnye	\N	f	От 2 кг,1900 руб/кг.	\N
1369	Торт N 240 д.	IMG_20230216_101416.jpg	sm-IMG_20230216_101416.jpg	detskie	\N	f	От 2,5 кг	\N
1370	Торт N 241 д.	IMG_20230216_101033.jpg	sm-IMG_20230216_101033.jpg	detskie	\N	f	От 2 кг	\N
1371	Торт 242 д.	IMG_20230216_101259.jpg	sm-IMG_20230216_101259.jpg	detskie	\N	f	Капкейки 	\N
1372	Торт N 243 д.	IMG_20230216_100910.jpg	sm-IMG_20230216_100910.jpg	detskie	\N	f	От 2 кг	\N
1373	Торт N 244 д.	IMG_20230216_100745.jpg	sm-IMG_20230216_100745.jpg	detskie	\N	f	От 2 кг	\N
1374	Торт N 245 д.	IMG_20230216_100501.jpg	sm-IMG_20230216_100501.jpg	detskie	\N	f	От 2 кг	\N
1375	Торт N 246 д.	IMG_20230216_100417.jpg	sm-IMG_20230216_100417.jpg	detskie	\N	f	От 2,5 кг	\N
1376	Торт N 54 к.	IMG_20230216_103311.jpg	sm-IMG_20230216_103311.jpg	corporativnye	\N	f	От 3 кг,1800 руб/кг.	\N
1377	Торт N 217 п.	IMG_20230216_103828.jpg	sm-IMG_20230216_103828.jpg	prazdnichnye	\N	f	От 1,5 кг	\N
1378	Торт N 218 п.	IMG_20230216_103357.jpg	sm-IMG_20230216_103357.jpg	prazdnichnye	\N	f	От 2 кг	\N
1379	Торт N 219 п.	IMG_20230216_103554.jpg	sm-IMG_20230216_103554.jpg	prazdnichnye	\N	f	От 2 кг	\N
1380	Торт N 220 п.	IMG_20230216_101454.jpg	sm-IMG_20230216_101454.jpg	prazdnichnye	\N	f	От 2 кг	\N
1381	Торт N 221 п.	IMG_20230216_101340.jpg	sm-IMG_20230216_101340.jpg	prazdnichnye	\N	f	От 2 кг	\N
1382	Торт N 222 п.	IMG_20230216_100711.jpg	sm-IMG_20230216_100711.jpg	prazdnichnye	\N	f	От 2,5 кг	\N
1383	Торт N 223 п.	IMG_20230216_100620.jpg	sm-IMG_20230216_100620.jpg	prazdnichnye	\N	f	От 3 кг	\N
1384	Торт N 58 с.	IMG_20230216_095203.jpg	sm-IMG_20230216_095203.jpg	svadebnye	\N	f	От 6 кг, \r\n	\N
1385	Торт N 224 п.	IMG_20230216_103804.jpg	sm-IMG_20230216_103804.jpg	prazdnichnye	\N	f	От 6 кг	\N
1386	Торт N 247д.	IMG_20230216_142342.jpg	sm-IMG_20230216_142342.jpg	detskie	\N	f	От 2 кг	\N
1388	Торт N 249д.	IMG_20230216_142029.jpg	sm-IMG_20230216_142029.jpg	detskie	\N	f	От 2 кг	\N
1389	Торт N 250 д.	IMG_20230216_141848.jpg	sm-IMG_20230216_141848.jpg	detskie	\N	f	Торт от 2 кг	\N
1390	Торт N 251 д.	IMG_20230216_141442.jpg	sm-IMG_20230216_141442.jpg	detskie	\N	f	От 2 кг	\N
1393	Торт N 254 д.	IMG_20230216_140428.jpg	sm-IMG_20230216_140428.jpg	detskie	\N	f	От 2,5 кг	\N
1395	Торт N 225 п.	IMG_20230216_142423.jpg	sm-IMG_20230216_142423.jpg	prazdnichnye	\N	f	От 2,5 кг	\N
1396	Торт N 226 п.	IMG_20230216_141943.jpg	sm-IMG_20230216_141943.jpg	prazdnichnye	\N	f	От2,5 кг	\N
1397	Торт N 227 п.	IMG_20230216_141743.jpg	sm-IMG_20230216_141743.jpg	prazdnichnye	\N	f	От 6 кг, 	\N
1398	Торт N 228 п.	IMG_20230216_141550.jpg	sm-IMG_20230216_141550.jpg	prazdnichnye	\N	f	Капкейки 	\N
1399	Торт N 229 п.	IMG_20230216_141505.jpg	sm-IMG_20230216_141505.jpg	prazdnichnye	\N	f	Торт от 2 кг	\N
1401	Торт N 231 п.	IMG_20230216_141300.jpg	sm-IMG_20230216_141300.jpg	prazdnichnye	\N	f	От 2,5 кг 	\N
1402	Торт N 232 п.	IMG_20230216_140903.jpg	sm-IMG_20230216_140903.jpg	prazdnichnye	\N	f	От 2 кг	\N
1403	Торт N 233 п .	IMG_20230216_140706.jpg	sm-IMG_20230216_140706.jpg	prazdnichnye	\N	f	От 2,5 кг	\N
1404	Торт N 234 п.	IMG_20230216_140609.jpg	sm-IMG_20230216_140609.jpg	prazdnichnye	\N	f	От 2 кг	\N
1405	Торт N 235 п.	IMG_20230216_135919.jpg	sm-IMG_20230216_135919.jpg	prazdnichnye	\N	f	От 3 кг	\N
1407	Торт N 55 к.	IMG_20230216_142256.jpg	sm-IMG_20230216_142256.jpg	corporativnye	\N	f	От 2 кг,1900 руб/кг 	\N
1408	Торт N 56 к.	IMG_20230216_142220.jpg	sm-IMG_20230216_142220.jpg	corporativnye	\N	f	От 2 кг, 1900 руб/кг.	\N
1409	Торт N 57 к.	IMG_20230216_141649.jpg	sm-IMG_20230216_141649.jpg	corporativnye	\N	f	От 3 кг ,1900 руб/кг 	\N
1410	Торт N 58 к.	IMG_20230216_141206.jpg	sm-IMG_20230216_141206.jpg	corporativnye	\N	f	От 5 кг, 1900 руб/кг	\N
1411	Торт N 59 к.	IMG_20230216_140038.jpg	sm-IMG_20230216_140038.jpg	corporativnye	\N	f	От 3 кг,1900 руб/кг 	\N
1412	Торт N 59 с.	IMG_20230216_134645.jpg	sm-IMG_20230216_134645.jpg	svadebnye	\N	f	От 5 кг, 	\N
1413	Торт N 237 п.	IMG_20210529_091431.jpg	sm-IMG_20210529_091431.jpg	prazdnichnye	\N	f	Капкейки 	\N
1414	Торт N 238 п.	IMG_20210521_095308.jpg	sm-IMG_20210521_095308.jpg	prazdnichnye	\N	f	От 1,5 кг	\N
1415	Торт N 239 п.	IMG_20230216_121222.jpg	sm-IMG_20230216_121222.jpg	prazdnichnye	\N	f	От 2 кг	\N
1416	Торт N 240 п.	IMG_20230216_121141.jpg	sm-IMG_20230216_121141.jpg	prazdnichnye	\N	f	Бенто торт 400-500 г.\r\n	\N
1417	Торт N 241 п.	IMG_20230216_121054.jpg	sm-IMG_20230216_121054.jpg	prazdnichnye	\N	f	От 2 кг	\N
1418	Торт N 242 п.	IMG_20230216_101809.jpg	sm-IMG_20230216_101809.jpg	prazdnichnye	\N	f	От 2 кг 	\N
1420	Торт № 60 к.	IMG_20230216_120916.jpg	sm-IMG_20230216_120916.jpg	corporativnye	\N	f	От 2 кг , 1800 руб/кг.	\N
1423	Торт N 246 п 	IMG_20230216_120246.jpg	sm-IMG_20230216_120246.jpg	prazdnichnye	\N	f	Бенто торт 400-500г.\r\n	\N
1424	Торт N 247 п .	IMG_20230216_153254.jpg	sm-IMG_20230216_153254.jpg	prazdnichnye	\N	f	Капкейки	\N
1427	Торт N 256 д.	IMG_20240615_072433.jpg	sm-IMG_20240615_072433.jpg	detskie	\N	f	От 2 кг	\N
1428	Торт 257 д.	IMG_20240609_122952.jpg	sm-IMG_20240609_122952.jpg	detskie	\N	f	От 2 кг 	\N
1430	Торт 259 д.	IMG_20240526_100905.jpg	sm-IMG_20240526_100905.jpg	detskie	\N	f	От 2 кг	\N
1431	Торт 260 д.	IMG_20240526_080028.jpg	sm-IMG_20240526_080028.jpg	detskie	\N	f	От 3 кг 	\N
1433	Торт N 262 д.	IMG_20240702_161232.jpg	sm-IMG_20240702_161232.jpg	detskie	\N	f	От 3 кг	\N
1434	Торт N263 д.	IMG_20240702_191529.jpg	sm-IMG_20240702_191529.jpg	detskie	\N	f	От 3 кг	\N
1436	Торт N 265 д.	IMG_20240702_191917.jpg	sm-IMG_20240702_191917.jpg	detskie	\N	f	От 3 кг 	\N
1437	Торт N 266 д.	IMG_20240702_192201.jpg	sm-IMG_20240702_192201.jpg	detskie	\N	f	От 2 кг	\N
1443	Торт N 272 д.	IMG_20240702_194059.jpg	sm-IMG_20240702_194059.jpg	detskie	\N	f	От 2 кг	\N
1444	Торт N 273 д.	IMG_20240702_194251.jpg	sm-IMG_20240702_194251.jpg	detskie	\N	f	От 2 кг	\N
1445	Торт N 274 д.	IMG_20240702_194519.jpg	sm-IMG_20240702_194519.jpg	detskie	\N	f	Бенто торт 400-500 гр\r\n	\N
1446	Торт N 275 д.	IMG_20240702_194840.jpg	sm-IMG_20240702_194840.jpg	detskie	\N	f	От 2 кг	\N
1447	Торт N 276 д.	IMG_20240702_195126.jpg	sm-IMG_20240702_195126.jpg	detskie	\N	f	От 2 кг	\N
1451	Торт N 280 д.	IMG_20240702_200254.jpg	sm-IMG_20240702_200254.jpg	detskie	\N	f	От 2,5 кг	\N
1452	Торт N 281 д.	IMG_20240702_200533.jpg	sm-IMG_20240702_200533.jpg	detskie	\N	f	От 2,5 кг	\N
1453	Торт N 282 д.	IMG_20240702_200737.jpg	sm-IMG_20240702_200737.jpg	detskie	\N	f	От 2 кг	\N
1454	Торт N 283 д.	IMG_20240702_201019.jpg	sm-IMG_20240702_201019.jpg	detskie	\N	f	От 2 кг	\N
1455	Торт N 284 д.	IMG_20240702_201746.jpg	sm-IMG_20240702_201746.jpg	detskie	\N	f	От 3 кг	\N
1456	Торт N 285 д.	IMG_20240702_201943.jpg	sm-IMG_20240702_201943.jpg	detskie	\N	f	От 2 кг	\N
1457	Торт N 286 д.	IMG_20240702_202406.jpg	sm-IMG_20240702_202406.jpg	detskie	\N	f	От 2 кг	\N
1458	Торт N 287 д.	IMG_20240702_210932.jpg	sm-IMG_20240702_210932.jpg	detskie	\N	f	От 3 кг	\N
1460	Торт N 289 д.	IMG_20240702_211349.jpg	sm-IMG_20240702_211349.jpg	detskie	\N	f	От 4 кг	\N
1461	Торт N 290 д.	IMG_20240702_211728.jpg	sm-IMG_20240702_211728.jpg	detskie	\N	f	От 2 кг	\N
1463	Торт N 292 д.	IMG_20240702_212338.jpg	sm-IMG_20240702_212338.jpg	detskie	\N	f	От 2,5 кг	\N
1464	Торт N 293 д.	IMG_20240702_212554.jpg	sm-IMG_20240702_212554.jpg	detskie	\N	f	От 2 кг	\N
1467	Торт N 296 д.	IMG_20240702_213635.jpg	sm-IMG_20240702_213635.jpg	detskie	\N	f	От 2 кг, 	\N
1468	Торт N 297 д.	IMG_20240702_213836.jpg	sm-IMG_20240702_213836.jpg	detskie	\N	f	От 2,5 кг	\N
1470	Торт N 299 д.	IMG_20240702_214350.jpg	sm-IMG_20240702_214350.jpg	detskie	\N	f	От 4 кг	\N
1471	Торт N 300 д.	IMG_20240702_214621.jpg	sm-IMG_20240702_214621.jpg	detskie	\N	f	От 2,5 кг	\N
1472	Торт N 301 д.	IMG_20240702_214826.jpg	sm-IMG_20240702_214826.jpg	detskie	\N	f	От 3 кг	\N
1473	Торт N 302 д.	IMG_20240702_215138.jpg	sm-IMG_20240702_215138.jpg	detskie	\N	f	От 2 кг	\N
1474	Торт N 303 д.	IMG_20240702_215414.jpg	sm-IMG_20240702_215414.jpg	detskie	\N	f	От 2,5 кг	\N
1476	Торт N 305 д.	IMG_20240704_123632.jpg	sm-IMG_20240704_123632.jpg	detskie	\N	f	От 2,5 кг	\N
1478	Торт N 307 д.	IMG_20240704_124448.jpg	sm-IMG_20240704_124448.jpg	detskie	\N	f	Торт от 2 кг	\N
1479	Торт N 308 д.	IMG_20240704_124731.jpg	sm-IMG_20240704_124731.jpg	detskie	\N	f	Торт от 2 кг	\N
1480	Торт N 309 д.	IMG_20240704_125019.jpg	sm-IMG_20240704_125019.jpg	detskie	\N	f	От 2 кг	\N
1482	Торт N 311 д.	IMG_20240704_201505.jpg	sm-IMG_20240704_201505.jpg	detskie	\N	f	От 3 кг	\N
1483	Торт N 312 д.	IMG_20240704_201706.jpg	sm-IMG_20240704_201706.jpg	detskie	\N	f	От 2,5 кг	\N
1484	Торт N 313 д.	IMG_20240704_201906.jpg	sm-IMG_20240704_201906.jpg	detskie	\N	f	От 2 кг	\N
1485	Торт N 314 д.	IMG_20240704_202110.jpg	sm-IMG_20240704_202110.jpg	detskie	\N	f	От 2,5 кг	\N
1486	Торт N 315 д.	IMG_20240704_202306.jpg	sm-IMG_20240704_202306.jpg	detskie	\N	f	От 3 кг	\N
1487	Торт N 316 д.	IMG_20240704_202524.jpg	sm-IMG_20240704_202524.jpg	detskie	\N	f	От 2,5 кг 	\N
1488	Торт N 317 д.	IMG_20240704_202740.jpg	sm-IMG_20240704_202740.jpg	detskie	\N	f	От 2,5 кг	\N
1489	Торта N 318 д.	IMG_20240704_203116.jpg	sm-IMG_20240704_203116.jpg	detskie	\N	f	От 2,5 кг	\N
1490	Торт N 319 д.	IMG_20240704_203332.jpg	sm-IMG_20240704_203332.jpg	detskie	\N	f	От 2,5 кг 	\N
1491	Торт N 320 д.	IMG_20240704_203948.jpg	sm-IMG_20240704_203948.jpg	detskie	\N	f	От 2 кг	\N
1492	Торт N 249 п.	IMG_20240704_204221.jpg	sm-IMG_20240704_204221.jpg	prazdnichnye	\N	f	От 4 кг	\N
1493	Торт N 250 п.	IMG_20240704_204452.jpg	sm-IMG_20240704_204452.jpg	prazdnichnye	\N	f	От 5 кг	\N
1494	Торт N 60 с.	IMG_20241210_081839.jpg	sm-IMG_20241210_081839.jpg	svadebnye	\N	f	От 4 кг.	\N
1495	Торт N 61 с.	IMG_20241210_082009.jpg	sm-IMG_20241210_082009.jpg	svadebnye	\N	f	От 3 кг,	\N
1496	Торт N 62 с.	IMG_20241210_082125.jpg	sm-IMG_20241210_082125.jpg	svadebnye	\N	f	От 3 кг,	\N
1497	Торт N 63 с.	IMG_20241210_082234.jpg	sm-IMG_20241210_082234.jpg	svadebnye	\N	f	От 2,5 кг	\N
1498	Торт N 64 с.	IMG_20241210_082337.jpg	sm-IMG_20241210_082337.jpg	svadebnye	\N	f	От 2 кг, 	\N
1499	Торт N 65 с.	IMG_20241210_082454.jpg	sm-IMG_20241210_082454.jpg	svadebnye	\N	f	От 6 кг,	\N
1500	Торт N 66 с.	IMG_20241210_083200.jpg	sm-IMG_20241210_083200.jpg	svadebnye	\N	f	От 2 кг,	\N
1501	Торт N 67 с.	IMG_20241210_083307.jpg	sm-IMG_20241210_083307.jpg	svadebnye	\N	f	От 2 кг 	\N
1502	Торт N 68 с.	IMG_20241210_083417.jpg	sm-IMG_20241210_083417.jpg	svadebnye	\N	f	От 6 кг	\N
1503	Торт N 69 с.	IMG_20241210_084259.jpg	sm-IMG_20241210_084259.jpg	svadebnye	\N	f	От 3,5 кг	\N
1504	Торт N 70 с.	IMG_20241210_084416.jpg	sm-IMG_20241210_084416.jpg	svadebnye	\N	f	От 2,5 кг	\N
1505	Торт N 71 с.	IMG_20241210_084747.jpg	sm-IMG_20241210_084747.jpg	svadebnye	\N	f	От 5 кг,	\N
1506	Торт N 72 с.	IMG_20241210_084621.jpg	sm-IMG_20241210_084621.jpg	svadebnye	\N	f	От 2,5 кг.	\N
1507	Торт N 73 с.	IMG_20241210_084528.jpg	sm-IMG_20241210_084528.jpg	svadebnye	\N	f	От 7 кг	\N
1508	Торт N 74.	IMG_20241210_110606.jpg	sm-IMG_20241210_110606.jpg	svadebnye	\N	f	От 3,5 кг	\N
1510	Торт N 322 д.	IMG_20241210_120128.jpg	sm-IMG_20241210_120128.jpg	detskie	\N	f	От 4 кг	\N
1511	Торт N 323 д.	IMG_20241210_124548.jpg	sm-IMG_20241210_124548.jpg	detskie	\N	f	От 2 кг	\N
1514	Торт N 326 д.	IMG_20241210_192447.jpg	sm-IMG_20241210_192447.jpg	detskie	\N	f	От 2 кг	\N
1517	Торт N 327 д.	IMG_20241210_124641.jpg	sm-IMG_20241210_124641.jpg	detskie	\N	f	От 2,5 кг	\N
1523	Торт N 331 д.	IMG_20241210_111955-(1).jpg	sm-IMG_20241210_111955-(1).jpg	detskie	\N	f	от 2 кг	\N
1524	Торт N 332 д	IMG_20241210_115234.jpg	sm-IMG_20241210_115234.jpg	detskie	\N	f	От 2 кг 	\N
1530	Торт N 251 п.	IMG_20241210_131419.jpg	sm-IMG_20241210_131419.jpg	prazdnichnye	\N	f	От 2 кг.	\N
1531	Торт N 252 п.	IMG_20241210_131335.jpg	sm-IMG_20241210_131335.jpg	prazdnichnye	\N	f	ОТ 1,5 кг	\N
1532	Торт N 253 п.	IMG_20241210_131509.jpg	sm-IMG_20241210_131509.jpg	prazdnichnye	\N	f	От 1,5 кг.	\N
1533	Торт N 255 п.	IMG_20241210_132933.jpg	sm-IMG_20241210_132933.jpg	prazdnichnye	\N	f	От 2 кг	\N
1535	Торт N 254 п.	IMG_20231230_085351.jpg	sm-IMG_20231230_085351.jpg	prazdnichnye	\N	f	От 2 кг	\N
1536	Торт 257 п.	IMG_20241210_170005.jpg	sm-IMG_20241210_170005.jpg	prazdnichnye	\N	f	От 2 кг	\N
1537	Торт N 258 п.	IMG_20241210_165924.jpg	sm-IMG_20241210_165924.jpg	prazdnichnye	\N	f	ОТ 2 кг	\N
1538	Торт N 259 п.	IMG_20241210_165822-(1).jpg	sm-IMG_20241210_165822-(1).jpg	prazdnichnye	\N	f	От 2,5 кг	\N
1539	Торт N 260 п.	IMG_20241210_165746.jpg	sm-IMG_20241210_165746.jpg	prazdnichnye	\N	f	От 2 кг	\N
1540	Торт N 261 п.	IMG_20241210_165708.jpg	sm-IMG_20241210_165708.jpg	prazdnichnye	\N	f	От 3 кг 	\N
1541	Торт N 262 п.	IMG_20241210_165622.jpg	sm-IMG_20241210_165622.jpg	prazdnichnye	\N	f	От 2 кг	\N
1542	Торт N 263 п.	IMG_20241210_165542.jpg	sm-IMG_20241210_165542.jpg	prazdnichnye	\N	f	От 4 кг .	\N
1544	Торт N 265 п.	IMG_20241210_165334.jpg	sm-IMG_20241210_165334.jpg	prazdnichnye	\N	f	От 2,5 кг	\N
1545	Торт N 266 п.	IMG_20241210_165046.jpg	sm-IMG_20241210_165046.jpg	prazdnichnye	\N	f	От 1,5 кг	\N
1546	Торт N 267 п.	IMG_20241210_164521.jpg	sm-IMG_20241210_164521.jpg	prazdnichnye	\N	f	Муссовый торт 1,1 кг	\N
1547	Торт N 268 п.	IMG_20241210_164411.jpg	sm-IMG_20241210_164411.jpg	prazdnichnye	\N	f	От 2,5 кг.	\N
1549	Торт N 270 п.	IMG_20241210_164004-(1).jpg	sm-IMG_20241210_164004-(1).jpg	prazdnichnye	\N	f	От 3,5 кг	\N
1550	Торт N 271 п.	IMG_20241210_163920.jpg	sm-IMG_20241210_163920.jpg	prazdnichnye	\N	f	От 3,5 кг	\N
1551	Торт N 272 п.	IMG_20241210_163709.jpg	sm-IMG_20241210_163709.jpg	prazdnichnye	\N	f	От 1,5 кг	\N
1552	Торт N 273 п.	IMG_20241210_163625.jpg	sm-IMG_20241210_163625.jpg	prazdnichnye	\N	f	От 2 кг	\N
1553	Торт N 274 п.	IMG_20241210_163401.jpg	sm-IMG_20241210_163401.jpg	prazdnichnye	\N	f	От 2 кг	\N
1554	Торт N 275 п.	IMG_20241210_163251.jpg	sm-IMG_20241210_163251.jpg	prazdnichnye	\N	f	От 2 кг	\N
1555	Торт N 276 п.	IMG_20241210_163230.jpg	sm-IMG_20241210_163230.jpg	prazdnichnye	\N	f	От 2,5 кг.	\N
1556	Торт N 277 п.	IMG_20241210_163157.jpg	sm-IMG_20241210_163157.jpg	prazdnichnye	\N	f	От 2,5 кг.	\N
1558	Торт N 279 п.	IMG_20241210_162807.jpg	sm-IMG_20241210_162807.jpg	prazdnichnye	\N	f	От 1,5 кг 	\N
1559	Торт N 280 п.	IMG_20241210_162727.jpg	sm-IMG_20241210_162727.jpg	prazdnichnye	\N	f	От 3,8 кг	\N
1560	Торт N 281 п.	IMG_20241210_162646.jpg	sm-IMG_20241210_162646.jpg	prazdnichnye	\N	f	От 2 кг 	\N
1562	Торт N 283 п.	IMG_20241210_162516.jpg	sm-IMG_20241210_162516.jpg	prazdnichnye	\N	f	От 4 кг	\N
1563	Торт N 284 п.	IMG_20241210_162416.jpg	sm-IMG_20241210_162416.jpg	prazdnichnye	\N	f	От 2,5 кг 	\N
1564	Торт N 285 п.	IMG_20241210_162328.jpg	sm-IMG_20241210_162328.jpg	prazdnichnye	\N	f	От 2,5 кг	\N
1565	Торт N 286 п.	IMG_20241210_161537.jpg	sm-IMG_20241210_161537.jpg	prazdnichnye	\N	f	От 3 кг.	\N
1566	Торт N 287 п.	IMG_20241210_161440.jpg	sm-IMG_20241210_161440.jpg	prazdnichnye	\N	f	От 3 кг	\N
1567	Торт N 288 п.	IMG_20241210_161348.jpg	sm-IMG_20241210_161348.jpg	prazdnichnye	\N	f	От 2 кг	\N
1568	Торт N 289 п.	IMG_20241210_161303.jpg	sm-IMG_20241210_161303.jpg	prazdnichnye	\N	f	От 2 кг	\N
1571	Торт N 292 п 	IMG_20240223_164041.jpg	sm-IMG_20240223_164041.jpg	prazdnichnye	\N	f	От 2 кг	\N
1572	Торт N 293 п.	IMG_20240223_163842.jpg	sm-IMG_20240223_163842.jpg	prazdnichnye	\N	f	От 2 кг	\N
1573	Торт N 294 п.	IMG_20240223_164213.jpg	sm-IMG_20240223_164213.jpg	prazdnichnye	\N	f	Торт от 3,5 кг	\N
1574	Торт N 295 п.	IMG_20240703_195642.jpg	sm-IMG_20240703_195642.jpg	prazdnichnye	\N	f	От 2,5 кг	\N
1575	Торт N 296 п.	IMG_20240223_163338.jpg	sm-IMG_20240223_163338.jpg	prazdnichnye	\N	f	Торт бомба, 1,8 кг	\N
1576	Торт N 297 п.	IMG_20240223_163552.jpg	sm-IMG_20240223_163552.jpg	prazdnichnye	\N	f	От 4 кг	\N
1577	Торт N 298 п.	IMG_20240223_163451.jpg	sm-IMG_20240223_163451.jpg	prazdnichnye	\N	f	От 2,5 кг	\N
1578	Торт N 299 п.	IMG_20240221_204016.jpg	sm-IMG_20240221_204016.jpg	prazdnichnye	\N	f	Муссовый торт 1,1 кг	\N
1579	Торт N 300 п.	IMG_20240221_203916.jpg	sm-IMG_20240221_203916.jpg	prazdnichnye	\N	f	От 2,5 кг	\N
1580	Торт N 301 п.	IMG_20241210_131244.jpg	sm-IMG_20241210_131244.jpg	prazdnichnye	\N	f	От 800 гр	\N
1581	Торт N 302 п.	IMG_20241210_131149.jpg	sm-IMG_20241210_131149.jpg	prazdnichnye	\N	f	Бенто торт 400-500 гр	\N
1582	Торт N 303 п.	IMG_20241210_131107.jpg	sm-IMG_20241210_131107.jpg	prazdnichnye	\N	f	Бенто торт 400-500 гр	\N
1583	Торт N 304 п.	IMG_20241210_131018.jpg	sm-IMG_20241210_131018.jpg	prazdnichnye	\N	f	Торт от 1 кг	\N
1584	Торт N 305 п.	IMG_20241210_130927.jpg	sm-IMG_20241210_130927.jpg	prazdnichnye	\N	f	Бенто торт 400-500 гр	\N
1585	Торт N 306 п.	IMG_20241210_130847.jpg	sm-IMG_20241210_130847.jpg	prazdnichnye	\N	f	Бенто торт 400-500 гр	\N
1586	Торт N 307 п.	IMG_20241210_130807.jpg	sm-IMG_20241210_130807.jpg	prazdnichnye	\N	f	Бенто торт 400-500 гр	\N
1587	Торт N 308 п.	IMG_20241210_130725.jpg	sm-IMG_20241210_130725.jpg	prazdnichnye	\N	f	Бенто торт 400-500 гр	\N
1588	Торт N 309 п.	IMG_20241210_130636.jpg	sm-IMG_20241210_130636.jpg	prazdnichnye	\N	f	Бенто торт 400-500 гр	\N
1589	Торт N 310 п.	IMG_20241210_130558.jpg	sm-IMG_20241210_130558.jpg	prazdnichnye	\N	f	Бенто торт 400-500 гр	\N
1590	Торт N61 к.	IMG_20241210_132626.jpg	sm-IMG_20241210_132626.jpg	corporativnye	\N	f	От 3 кг, 1900 руб за кг.	\N
1591	Торт N 62 к.	IMG_20241210_132549.jpg	sm-IMG_20241210_132549.jpg	corporativnye	\N	f	От 3 кг,1800 руб за кг.	\N
1592	Торт N 63 к.	IMG_20241210_132511.jpg	sm-IMG_20241210_132511.jpg	corporativnye	\N	f	От 3 кг, 1900 руб за кг.	\N
1593	Торт N 64 к.	IMG_20241210_132427.jpg	sm-IMG_20241210_132427.jpg	corporativnye	\N	f	От 3 кг, 1900 руб за кг.	\N
1594	Торт N 65 к.	IMG_20241210_132349.jpg	sm-IMG_20241210_132349.jpg	corporativnye	\N	f	ОТ 3 кг, 1900 руб за кг.	\N
1595	Торт N 66 к 	IMG_20241210_132259.jpg	sm-IMG_20241210_132259.jpg	corporativnye	\N	f	От 3 кг, 2000 руб за кг.	\N
1596	Торт N 67 к.	IMG_20241210_132216.jpg	sm-IMG_20241210_132216.jpg	corporativnye	\N	f	От 2 кг, 1900 руб за кг.	\N
1597	Торт N 68 к.	IMG_20241210_132135-(1).jpg	sm-IMG_20241210_132135-(1).jpg	corporativnye	\N	f	От 3,5 кг, 2000 руб за кг.	\N
1598	Торт N 69 к.	IMG_20241210_132033.jpg	sm-IMG_20241210_132033.jpg	corporativnye	\N	f	От 2 кг, 1900 руб за кг.	\N
1599	Торт N 70 к.	IMG_20241210_131937.jpg	sm-IMG_20241210_131937.jpg	corporativnye	\N	f	От 2 кг, 1900 руб за кг.	\N
1600	Торт N 71 к.	IMG_20241210_131834.jpg	sm-IMG_20241210_131834.jpg	corporativnye	\N	f	Торт от 2 кг, 1900 руб за кг.	\N
1601	Торт N 72 к.	IMG_20241210_134025.jpg	sm-IMG_20241210_134025.jpg	corporativnye	\N	f	Пирожные 1 шт.350 руб.	\N
1602	Торт N 311 п.	IMG_20241211_120309.jpg	sm-IMG_20241211_120309.jpg	prazdnichnye	\N	f	От 4 кг	\N
1603	Торт N 312 п.	IMG_20241211_120217.jpg	sm-IMG_20241211_120217.jpg	prazdnichnye	\N	f	От 3,5 кг	\N
1604	Торт N 313 п.	IMG_20241211_120129.jpg	sm-IMG_20241211_120129.jpg	prazdnichnye	\N	f	От 3 кг	\N
1605	Торт N314 п.	IMG_20241211_115937.jpg	sm-IMG_20241211_115937.jpg	prazdnichnye	\N	f	От 5 кг 	\N
1606	Торт N 315 п.	IMG_20241211_115854.jpg	sm-IMG_20241211_115854.jpg	prazdnichnye	\N	f	От 3,5 кг 	\N
1607	Торт N 316 п.	IMG_20241211_115804.jpg	sm-IMG_20241211_115804.jpg	prazdnichnye	\N	f	От 1,5 кг 	\N
1608	Торт N 317 п.	IMG_20241211_115709.jpg	sm-IMG_20241211_115709.jpg	prazdnichnye	\N	f	От 3 кг	\N
1609	Торт N 318 п.	IMG_20241211_115621.jpg	sm-IMG_20241211_115621.jpg	prazdnichnye	\N	f	От 3 кг	\N
1610	Торт N 319 п.	IMG_20241211_115542.jpg	sm-IMG_20241211_115542.jpg	prazdnichnye	\N	f	От 1,5 кг 	\N
1611	Торт N 320 п.	IMG_20241211_115451.jpg	sm-IMG_20241211_115451.jpg	prazdnichnye	\N	f	От 3,5 кг     	\N
1612	Торт N 321 п.	IMG_20241211_115411.jpg	sm-IMG_20241211_115411.jpg	prazdnichnye	\N	f	От 3,5 кг	\N
1613	Торт N 322 п.	IMG_20241211_115317.jpg	sm-IMG_20241211_115317.jpg	prazdnichnye	\N	f	От 3,5 кг	\N
1614	Торт N 323 п.	IMG_20241211_115229.jpg	sm-IMG_20241211_115229.jpg	prazdnichnye	\N	f	От 3 кг	\N
1615	Торт N 324 п.	IMG_20241211_115128.jpg	sm-IMG_20241211_115128.jpg	prazdnichnye	\N	f	От 2,5 кг	\N
1616	Торт N 325 п.	IMG_20241211_115022.jpg	sm-IMG_20241211_115022.jpg	prazdnichnye	\N	f	От 2 кг.	\N
1617	Торт N 326 п.	IMG_20241211_114926.jpg	sm-IMG_20241211_114926.jpg	prazdnichnye	\N	f	От 2,5 кг	\N
1618	Торт N 327 п.	IMG_20241211_114825.jpg	sm-IMG_20241211_114825.jpg	prazdnichnye	\N	f	От 2,5 кг	\N
1619	Торт N 328 п.	IMG_20241211_114730-(1).jpg	sm-IMG_20241211_114730-(1).jpg	prazdnichnye	\N	f	От 2,5 кг	\N
1620	Торт N 329 п.	IMG_20241211_114641.jpg	sm-IMG_20241211_114641.jpg	prazdnichnye	\N	f	От 1,5 кг	\N
1621	Торт N 330 п.	IMG_20241211_114549.jpg	sm-IMG_20241211_114549.jpg	prazdnichnye	\N	f	От 5 кг	\N
1622	Торт N 331 п.	IMG_20241211_114456.jpg	sm-IMG_20241211_114456.jpg	prazdnichnye	\N	f	От 2 кг	\N
1623	Торт N 332 п 	IMG_20241211_114416.jpg	sm-IMG_20241211_114416.jpg	prazdnichnye	\N	f	От 2,5 кг	\N
1624	Торт N 333 п.	IMG_20241211_114329.jpg	sm-IMG_20241211_114329.jpg	prazdnichnye	\N	f	От 4 кг	\N
1625	Пирожные N 334 п.	IMG_20241210_161022.jpg	sm-IMG_20241210_161022.jpg	prazdnichnye	\N	f	Капкейк 	\N
1626	Пирожные N 335 п.	IMG_20241210_160906.jpg	sm-IMG_20241210_160906.jpg	prazdnichnye	\N	f	Капкейк 	\N
1627	Пирожные N 336 п.	IMG_20241210_160827.jpg	sm-IMG_20241210_160827.jpg	prazdnichnye	\N	f	Капкейк 	\N
1628	Пирожные N 337 п.	IMG_20241210_160726.jpg	sm-IMG_20241210_160726.jpg	prazdnichnye	\N	f	Капкейк 	\N
1629	Пирожные N 338 п.	IMG_20241210_160632.jpg	sm-IMG_20241210_160632.jpg	prazdnichnye	\N	f	Капкейк 	\N
1630	Пирожные N 339 п.	IMG_20241210_160511.jpg	sm-IMG_20241210_160511.jpg	prazdnichnye	\N	f	Капкейк 	\N
1631	Пирожные N 340 п.	IMG_20241210_160417.jpg	sm-IMG_20241210_160417.jpg	prazdnichnye	\N	f	Капкейк 	\N
1632	Пирожные N 341 п.	IMG_20241210_160313.jpg	sm-IMG_20241210_160313.jpg	prazdnichnye	\N	f	Капкейк 	\N
1633	Пирожные N 342 п.	IMG_20241210_155856.jpg	sm-IMG_20241210_155856.jpg	prazdnichnye	\N	f	Трайфл 	\N
1634	Пирожные N 343 п.	IMG_20241210_155622.jpg	sm-IMG_20241210_155622.jpg	prazdnichnye	\N	f	Капкейк 	\N
1635	Пирожные N 344 п.	IMG_20241210_155536.jpg	sm-IMG_20241210_155536.jpg	prazdnichnye	\N	f	Капкейк 	\N
1636	Пирожные N 345 п.	IMG_20241210_155443.jpg	sm-IMG_20241210_155443.jpg	prazdnichnye	\N	f	Капкейк 	\N
1637	Пирожные N 346 п.	IMG_20241210_155356.jpg	sm-IMG_20241210_155356.jpg	prazdnichnye	\N	f	Капкейк 	\N
1638	Пирожные N 347 п.	IMG_20241210_133917.jpg	sm-IMG_20241210_133917.jpg	prazdnichnye	\N	f	Трайфл 	\N
1639	Пирожные N 348 п.	IMG_20241210_133800.jpg	sm-IMG_20241210_133800.jpg	prazdnichnye	\N	f	Капкейк	\N
1640	Пирожные N 349 п.	IMG_20241210_133438.jpg	sm-IMG_20241210_133438.jpg	prazdnichnye	\N	f	Капкейк	\N
1641	Пирожные N 350 п.	IMG_20241210_133056.jpg	sm-IMG_20241210_133056.jpg	prazdnichnye	\N	f	Капкейк	\N
1643	Пирожные  N 334 д.	IMG_20241210_133837.jpg	sm-IMG_20241210_133837.jpg	detskie	\N	f	Кейкпопсы 	\N
\.


--
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Categories" ("Id", "Slug", "Name", "Description", "SortOrder") FROM stdin;
1	detskie	Детские	Ничто так не радует детей, как тортик с любимыми героями из сказок и мультфильмов. Ведь для детей торт — это не просто сладкое лакомство, а ожидание сюрприза и сказки. Торт запомнится ребенку надолго! Сделайте праздник ярче!	1
2	prazdnichnye	Праздничные	Праздник — это всегда радостное событие. А что может быть приятнее, чем порадовать своих родных или друзей, заказав красивый праздничный торт. Изготовим отличный торт для Вашего торжества или просто хорошего настроения!	2
3	corporativnye	Корпоративные	Корпоративный торт помогает создавать особое праздничное настроение и становится самой значимой частью торжества. Необычные торты делают праздник оригинальным и помогают в работе над созданием корпоративного духа!	4
4	svadebnye	Свадебные	Свадебный торт — это традиционная кульминация торжества по случаю бракосочетания. Всегда хочется удивить гостей не только вкусом, но и внешним видом торта! Впечатления от шикарного свадебного торта останутся на всю жизнь!	3
\.


--
-- Data for Name: ContactSettings; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."ContactSettings" ("Id", "Phone", "AdditionalPhone", "Email", "Address", "MapUrl") FROM stdin;
1	+7 913 987 2554	\N	79139872554@yandex.ru	\N	\N
\.


--
-- Data for Name: ContentBlocks; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."ContentBlocks" ("Id", "PageId", "Title", "Text", "ImageUrl", "SortOrder") FROM stdin;
1	4	Как заказать	<p>Заказы принимаются с 10.00 до 18.00</p>\r\n\r\n<p>Продукция от 2-5 кг., оплачивается при получении. От 5 кг авансовая система (50%).</p>\r\n\r\n<p>Оформление происходит в удобном для Вас месте.</p>\r\n\r\n<p>Торты индивидуально и празднично упакованы.</p>\r\n\r\n<p>При необходимости возможны ускоренные заказы.</p>\r\n\r\n<p>Ваши индивидуальные сценарии по оформлению и начинке торта можно обсудить с шеф кондитером.</p>\r\n	IMG_20240703_204455.jpg	1
2	4	Доставка	<p>Доставка ежедневно с 10.00 до 20.00.</p>\r\n\r\n<p>Интервал 3 час.</p>\r\n\r\n<p>Левый берег &ndash; 400 руб.</p>\r\n\r\n<p>ОбьГЭС и Васхнил &ndash; 600 руб.</p>\r\n\r\n<p>г. Обь - 700 руб.</p>\r\n\r\n<p>Правый берег &ndash; 500 руб.</p>\r\n\r\n<p>Академгородок и Бердск &ndash; 1000 руб.</p>\r\n\r\n<p>&nbsp;</p>\r\n	IMG_20240703_204802.jpg	2
\.


--
-- Data for Name: Fillings; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Fillings" ("Id", "Name", "Description", "ImageUrl", "HasCrossSection") FROM stdin;
1	Бабушкин	Ароматный ягодный бисквит, легкая кефирная пропитка и нежнейшие сливки	IMG_20230418_192308.jpg	t
2	Дамские пальчики	Заварные печеньки пропитаны деревенской сметанкой, чудесное сочетание	IMG_20230418_191722.jpg	t
3	Райская сказка	Домашний сметанный бисквит , пять коржей с добавлением кураги , чернослива ,грецкого ореха , мака и изюма.\r\nПропитан сметаной пропиткой и сливочным кремом с 	IMG_20230418_192111.jpg	t
4	Шоколадный классический 	Классический бисквит с добавлением тёмного шоколада и сливочно-шоколадный крем.	IMG_20230418_191538.jpg	t
6	Торт черный лес 	Шоколадные коржи пропитанные вишнёвым сиропом , крем взбитые сливки с добавлением вишни.	IMG_20230418_192548.jpg	t
7	Сметанник 	Нежнейшие сметанные коржи пропитанные сметанным кремом с добавлением персика , груши , банана, клубники на выбор или без  добавок.	IMG_20230418_191259.jpg	t
8	Йогуртовый	Тонкие бисквитные коржи на основе сгущённого молока , крем взбитые сливки с добавлением йогурта и на выбор клубники, вишни, груши, банана, персика, киви.	IMG_20230418_192944.jpg	t
15	Медовый с карамельным кремом	Ароматные коржи с добавлением мёда с заврным сливочно- карамельным кремом.	IMG_20230418_190847.jpg	t
16	Морковный	Ореховый бисквит с добавлением сочной моркови и сливочного крема.	IMG_20230418_190455.jpg	t
17	Черёмуховый	Ароматный черёмуховый бисквит сметанная пропитка и нежный сливочный крем.	IMG_20230418_182359.jpg	t
19	Каремельно-ореховый	Шоколадные бисквиты пропитанные сметанной пропиткой крем сливки взбитые с вареной сгущенкой и грецким орехом.	IMG_20230418_190244.jpg	t
22	Медовый со сметанным кремом	Ароматные коржи с добавлением мёда пропитанные деревенской сметаной.	IMG_20230418_182724.jpg	t
25	Сникерс	Пропитанные шоколадные коржи с вареной сгущенкой и грецким орехом , крем чиз на сливках.	IMG_20230418_181424.jpg	t
27	Красный бархат 	Сочные бисквитные коржи с лёгкой ноткой шоколада , прослойка сливочный крем с добавлением творожного сыра.	IMG_20230418_194121.jpg	t
\.


--
-- Data for Name: Orders; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Orders" ("Id", "CreatedAt", "CustomerName", "CustomerPhone", "CustomerEmail", "CakeId", "CustomCakeDescription", "FillingId", "Weight", "DeliveryDate", "DeliveryAddress", "Status", "Comment") FROM stdin;
\.


--
-- Data for Name: Pages; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Pages" ("Id", "Slug", "Title", "MetaDescription", "Heading", "Subheading", "Content") FROM stdin;
1	index	Торты на заказ в Новосибирске! Кондитерская студия El Torto!	Кондитерская студия El Torto делает торты на заказ в Новосибирске с доставкой. Красиво и очень вкусно! Детские, свадебные и корпоративные торты. Смотрите на сайте!	Студия EL TORTO	Торты на заказ в Новосибирске! В нашем каталоге более пятисот работ, профессионально исполненных для Вас!	\N
2	portfolio				\N	\N
3	nachinki	Превосходные начинки для тортов! Кондитерская студия El Torto, Новосибирск!	Кондитерская студия El Torto делает торты на заказ в Новосибирске с доставкой. Красиво и очень вкусно! Детские, свадебные и корпоративные торты. Смотрите на сайте!		Мы выбрали самые популярные начинки, Вы можете придумать свою &mdash; уникальную и оригинальную!	\N
4	zakaz-i-dostavka	Заказ и доставка тортов в Новосибирске! Закажите в El Torto!	Кондитерская студия El Torto делает торты на заказ в Новосибирске с доставкой. Красиво и очень вкусно!		Узнайте как заказать любой из понравившихся тортов из каталога или придумать свой.	\N
5	otzyvy	Отзывы о продукции El Torto в Новосибирске!	Кондитерская студия El Torto делает торты на заказ в Новосибирске с доставкой. Красиво и очень вкусно!		Здесь можно похвалить нас или пожаловаться, мы очень ждем  ваших отзывов.	\N
6	contacts	Контакты кондитерской студии El Torto в Новосибирске	Кондитерская студия El Torto делает торты на заказ в Новосибирске с доставкой. Красиво и очень вкусно!		С нами легко связаться и сделать заказ! Закажите торт у нас и почувствуйте разницу!	\N
7	detskie	Детский торт на заказ в Новосибирске! Любой дизайн! Закажите в El Torto!	Лучший подарок - детский торт с любимыми сказочными или мультяшными героями. Подарите ребенку сказку!	Детские торты	Лучший подарок - детский торт с любимыми сказочными или мультяшными героями.\nПодарите ребенку сказку!	\N
8	prazdnichnye	Торт на праздник в Новосибирске! Любой формы и веса! Закажите в El Torto!	Главное действующее лицо праздничного чаепития, один из лучших знаков внимания к друзьям и близким!	Праздничные торты	Главное действующее лицо праздничного чаепития, один из лучших знаков внимания к друзьям и близким!	\N
9	svadebnye	Свадебный торт на заказ! Великолепный дизайн и сказочный вкус! Закажите в El Torto!	Кондитерская студия El Torto изготовит торт для свадебного торжества. Он будет сказочно красивым и оригинальным!	Свадебные торты	Торт – это кульминация свадебного торжества. Пусть он будет сказочно красивым и оригинальным!	\N
10	corporativnye	Торты на корпоратив! Логотип компании в виде вкусного торта! Закажите в EL Torto!	Кондитерская студия El Torto изготовит на заказ корпоративный торт любой формы, размера и веса! Безумно вкусно и оригинально!	Корпоративные торты	Отличный способ отобразить  успехи вашей компании, ключевым элементом которого станет  красивый логотип!	\N
\.


--
-- Data for Name: SliderItems; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."SliderItems" ("Id", "ImageUrl", "Title", "Subtitle", "SortOrder") FROM stdin;
1	IMG_20240703_200553.jpg	Наслаждение вкусом	\N	1
2	IMG_20240703_203227.jpg	Восхитительные начинки	\N	2
3	IMG_20240703_203313.jpg	Со свежими фруктами	\N	3
4	IMG_20240703_200231.jpg	Настоящее удовольствие	\N	4
5	IMG_20240703_202554.jpg	Сделано с любовью	\N	5
\.


--
-- Data for Name: Testimonials; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Testimonials" ("Id", "Date", "Author", "Email", "Text", "Response", "IsApproved") FROM stdin;
1	2012-11-05 16:09:00+00	Олеся	rrodion@mail.ru	Огромное спасибо за Ваш торт "жемчужина", родители и гости были в восторге, еле уговорили разрезать торт, а ели так вообще с удовольствием!!! Очень вкусно!	\N	t
2	2012-12-08 09:36:00+00	Ирина	gordeyka86@bk.ru	<p>Здравствуйте!хотим вас поблагодарить и сказать большущее спасибо за умопомрачительный,сказочный,наивкуснейший и очень яркий тортик &quot;&quot;!!!Нашей малышке он безумно понравился,она была в восторге от своих любимых персонажей :)День рождения прошел на УРА!</p>\r\n	\N	t
3	2012-12-29 08:47:00+00	Любовь	zzzlubazzz@mail.ru	Большое спасибо за великолепный и наивкуснейший торт! Безумно порадовало соотношение цены,красоты и вксноты!)))Заказали еще и будем заказывать дальше!	\N	t
4	2013-03-07 17:33:00+00	Вадим	vadim_333@mail.ru	Хочу поздравить лучшую "половину" студии El Torto с праздником весны.Здоровья вам,удачи,успехов во всем.Пусть все у вас в жизни будет такое же "сладкое" и изысканное,как то,чем вы радуете нас и наших близких.Спасибо вам за то,что вы есть!!!!!!!!	\N	t
5	2013-06-11 20:58:00+00	Надежда	Fetnad2007@yandex.ru	Тортик вкусный до безумения (дочь 6 лет). Всем очень понравился, просто растаял во рту.	\N	t
6	2013-06-20 21:40:00+00	Ольга	54n@mail.ru	Заказали торт на день рождения ребенка и .. остались очень довольны и внешним видом торта и его вкусом) Особенно порадовало то, что кондитер точно воспроизвел торт, который я предварительно отправила на фото - и цвет, и машинки, и дорожные знаки, абсолютно всё, как на фотографии. Сразу было видно, что работал профессионал. Упаковка торта в реальности выглядит намного лучше , чем на фотографии (см. сайт) - празднично и со вкусом. Спасибо большое за Ваш талант! Торт понравился всем гостям)))	\N	t
7	2013-07-29 09:58:00+00	Татьяна	gibtk@mail.ru	Огромное спасибо, за такой чудесно красивый и очень вкусный торт для нашего Вовочки, в честь его первого юбилея!!! Все гости были в восторге от этого произведения искусства! Торт наш был индивидуален и на нем можно было увидеть предпочтения нашего сына:  любимая книга, любимые герои мультфильмов))))СПАСИБО!!! 	\N	t
8	2013-08-18 11:22:00+00	Александра	alexandra_pro1@mail.ru	Заказали сыну на 5 лет тортик.Пусть и с небольшими неровностями мы получили наш тортик, но качество и очень красивое оформление сгладили все это! Торт очень! вкусный, начинка обалденная. Большое спасибо	\N	t
9	2013-09-08 11:05:00+00	Елена	ena198461@rambler.ru	Доброго времени суток! Хочу сказать огромное спасибо за тортик! Он был очень вкусен( йогуртовый с грушей), такой нежный-как и обещали! Шикарное оформление-все гости в восторге! Удачи Вам! 	\N	t
11	2013-09-27 09:14:00+00	Наталья	poliankana@mail.ru	Торт изумительный! Подушечка с розой, выше всяких похвал, получилась! Очень красиво! Роза прям как настоящая!\r\nА вкус...м-м-м-м...ВКУСНЯТИНА!Дочка и все гости были в восторге!\r\nЕщё раз СПАСИБО за ваш шедевр!!!\r\nЗаказывала на 8 сентября. Доставили вовремя и упаковка торта была чудесная)	\N	t
12	2013-12-18 09:45:00+00	Юля	julia@solodukhina.ru	<p>Заказывали детский торт со &nbsp;на День Рождения сына! Торт превзошел все ожидания! Настоящее произведение искусства! Герои&nbsp;сделаны очень аккуратно, точь-в-точь как в мульте! Поразили мелкие детали(косичка у Нюши, цветы, божьи коровки, очки у Ежа). На вкус торт тоже очень-очень вкусный(брали сметанный с персиками), очень нежная начинка. гостям тоже очень понравилось! В следующий раз торт будем брать только у вас! Спасибо большое!</p>\r\n	\N	t
18	2014-10-15 12:08:00+00	Марина	marinatolstova@yandex.ru	Торт был безумно красивый, так все великолепно проработано... а на вкус просто пальчики оближешь))) Спасибо Юля!	\N	t
20	2016-02-25 16:07:00+00	Елена	sunnylena@mail.ru	<p>Тортик к Празднику получили великолепный! И красивый: яркий мультяшный рисунок, без веской мастики (как и хотели!), наинежнейший и наивкуснейший! Спасибо большое Юлии и всем принимавшим участие в изготовлении и доставке в срок (прям ровно в назначенное время - что немаловажно)! Не прощаемся :)</p>\r\n	\N	t
25	2020-07-24 14:46:00+00	Юлия	Kravtsova_yuliya@mail.ru	<p>ЗАКАЗЫВАЮ тОрты только тут! Всегда очень вкусные и неЖные начинки. Любой диЗайн!!!!&nbsp; Торты пОлучаются-произведение Искусства!!! АккуРатно и проработаны даже мельчайшие детали!!! Спасибо вам !!!!</p>\r\n	\N	t
30	2025-03-29 09:11:00+00	Софья 	turutinasofa3@gmail.com	<p>Заказываю торты постоянно, очень нравится, вкусно и красиво!!!</p>\r\n	\N	t
670	2026-03-08 17:32:00+00	Barryerock	\N	Ты plan отправиться, тебе важно know условия. Но site doesnt respond. \r\nМы предусмотрели резерв, как у kraken официальный сайт. algorithm switches соединение. \r\nТы просто переходишь и watch данные. \r\nссылка кракен	\N	f
671	2026-03-08 20:09:00+00	CrystalImpot	+12075966781	Want a hot girl? \r\nMeet her right now!	\N	f
672	2026-03-09 03:53:00+00	StevenGok	\N	Здравствуйте! \r\n \r\nСлучайно зашел на Ваш сайт - по всей видимости ему требуется доработка. \r\n \r\nМеня зовут Сергей. Я много лет занимаюсь создание web сайтов любого уровня сложности. \r\n \r\nЯ могу предложить: \r\n- Разработать новый сайт с нуля; \r\n- Доработать Ваш существующий сайт; \r\n- Заниматься дальнейшей поддержкой сайта; \r\n- Обновлять контент; \r\n- Развивать и модернизировать сайт - добавлять новые функции и сервисы. \r\n \r\nМои услуги стоят недорого. \r\n \r\nПожалуйста сообщите - планируете ли Вы в ближайшем будущем создание нового сайта или внесение поправки в Ваш существующий сайт. Если да - кратко опишите что планируете разработать - в ответ я рассчитаю стоимость разработок и предложу различные варианты. \r\n \r\nС уважением, Сергей. \r\n \r\nМой email: uplilmbilt@bk.ru	\N	f
673	2026-03-09 16:48:00+00	bazaPleni	\N	Дoброгo времени cуток, прeдлaгаю бaзы лиц принимaющих рeшeние, ваших пoтeнциальныx пoкупатeлeй. Пишитe, eсли интeреснo на telegramm baza01234	\N	f
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260319191245_InitialCreate	8.0.11
\.


--
-- Data for Name: __MigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__MigrationsHistory" ("Id", "MigrationName", "AppliedDate", "Details") FROM stdin;
1	2026_03_20_InitialData	2026-03-19 19:19:11.142738	Initial data migration from MySQL
\.


--
-- Name: Cakes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Cakes_Id_seq"', 1643, true);


--
-- Name: Categories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Categories_Id_seq"', 4, true);


--
-- Name: ContactSettings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."ContactSettings_Id_seq"', 1, true);


--
-- Name: ContentBlocks_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."ContentBlocks_Id_seq"', 2, true);


--
-- Name: Fillings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Fillings_Id_seq"', 27, true);


--
-- Name: Orders_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Orders_Id_seq"', 1, false);


--
-- Name: Pages_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Pages_Id_seq"', 10, true);


--
-- Name: SliderItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."SliderItems_Id_seq"', 5, true);


--
-- Name: Testimonials_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Testimonials_Id_seq"', 673, true);


--
-- Name: __MigrationsHistory_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."__MigrationsHistory_Id_seq"', 1, true);


--
-- Name: Categories AK_Categories_Slug; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "AK_Categories_Slug" UNIQUE ("Slug");


--
-- Name: Cakes PK_Cakes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Cakes"
    ADD CONSTRAINT "PK_Cakes" PRIMARY KEY ("Id");


--
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- Name: ContactSettings PK_ContactSettings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ContactSettings"
    ADD CONSTRAINT "PK_ContactSettings" PRIMARY KEY ("Id");


--
-- Name: ContentBlocks PK_ContentBlocks; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ContentBlocks"
    ADD CONSTRAINT "PK_ContentBlocks" PRIMARY KEY ("Id");


--
-- Name: Fillings PK_Fillings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Fillings"
    ADD CONSTRAINT "PK_Fillings" PRIMARY KEY ("Id");


--
-- Name: Orders PK_Orders; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "PK_Orders" PRIMARY KEY ("Id");


--
-- Name: Pages PK_Pages; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Pages"
    ADD CONSTRAINT "PK_Pages" PRIMARY KEY ("Id");


--
-- Name: SliderItems PK_SliderItems; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SliderItems"
    ADD CONSTRAINT "PK_SliderItems" PRIMARY KEY ("Id");


--
-- Name: Testimonials PK_Testimonials; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Testimonials"
    ADD CONSTRAINT "PK_Testimonials" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: __MigrationsHistory __MigrationsHistory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__MigrationsHistory"
    ADD CONSTRAINT "__MigrationsHistory_pkey" PRIMARY KEY ("Id");


--
-- Name: IX_Cakes_CategorySlug; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Cakes_CategorySlug" ON public."Cakes" USING btree ("CategorySlug");


--
-- Name: IX_Cakes_FillingId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Cakes_FillingId" ON public."Cakes" USING btree ("FillingId");


--
-- Name: IX_Cakes_IsFeatured; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Cakes_IsFeatured" ON public."Cakes" USING btree ("IsFeatured");


--
-- Name: IX_Categories_Slug; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Categories_Slug" ON public."Categories" USING btree ("Slug");


--
-- Name: IX_Categories_SortOrder; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Categories_SortOrder" ON public."Categories" USING btree ("SortOrder");


--
-- Name: IX_ContactSettings_Single; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ContactSettings_Single" ON public."ContactSettings" USING btree ("Id");


--
-- Name: IX_ContentBlocks_PageId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ContentBlocks_PageId" ON public."ContentBlocks" USING btree ("PageId");


--
-- Name: IX_ContentBlocks_PageId_SortOrder; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ContentBlocks_PageId_SortOrder" ON public."ContentBlocks" USING btree ("PageId", "SortOrder");


--
-- Name: IX_Fillings_Name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Fillings_Name" ON public."Fillings" USING btree ("Name");


--
-- Name: IX_Orders_CakeId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Orders_CakeId" ON public."Orders" USING btree ("CakeId");


--
-- Name: IX_Orders_CreatedAt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Orders_CreatedAt" ON public."Orders" USING btree ("CreatedAt");


--
-- Name: IX_Orders_CustomerPhone; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Orders_CustomerPhone" ON public."Orders" USING btree ("CustomerPhone");


--
-- Name: IX_Orders_DeliveryDate; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Orders_DeliveryDate" ON public."Orders" USING btree ("DeliveryDate");


--
-- Name: IX_Orders_FillingId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Orders_FillingId" ON public."Orders" USING btree ("FillingId");


--
-- Name: IX_Orders_Status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Orders_Status" ON public."Orders" USING btree ("Status");


--
-- Name: IX_Pages_Slug; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Pages_Slug" ON public."Pages" USING btree ("Slug");


--
-- Name: IX_SliderItems_SortOrder; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_SliderItems_SortOrder" ON public."SliderItems" USING btree ("SortOrder");


--
-- Name: IX_Testimonials_Date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Testimonials_Date" ON public."Testimonials" USING btree ("Date");


--
-- Name: IX_Testimonials_IsApproved; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Testimonials_IsApproved" ON public."Testimonials" USING btree ("IsApproved");


--
-- Name: Cakes FK_Cakes_Categories_CategorySlug; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Cakes"
    ADD CONSTRAINT "FK_Cakes_Categories_CategorySlug" FOREIGN KEY ("CategorySlug") REFERENCES public."Categories"("Slug") ON DELETE RESTRICT;


--
-- Name: Cakes FK_Cakes_Fillings_FillingId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Cakes"
    ADD CONSTRAINT "FK_Cakes_Fillings_FillingId" FOREIGN KEY ("FillingId") REFERENCES public."Fillings"("Id") ON DELETE SET NULL;


--
-- Name: ContentBlocks FK_ContentBlocks_Pages_PageId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ContentBlocks"
    ADD CONSTRAINT "FK_ContentBlocks_Pages_PageId" FOREIGN KEY ("PageId") REFERENCES public."Pages"("Id") ON DELETE CASCADE;


--
-- Name: Orders FK_Orders_Cakes_CakeId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "FK_Orders_Cakes_CakeId" FOREIGN KEY ("CakeId") REFERENCES public."Cakes"("Id") ON DELETE SET NULL;


--
-- Name: Orders FK_Orders_Fillings_FillingId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "FK_Orders_Fillings_FillingId" FOREIGN KEY ("FillingId") REFERENCES public."Fillings"("Id") ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict UdkMZFzhJbg11GAu4ikOKzn5RU9qkFRYswURPgnzPHu6gszUjdIkcnd4sBggMPr

