error_log /dev/null emerg;

log_format simple '$remote_addr - $remote_user [$time_local] "$request" '
                  '$status $body_bytes_sent "$http_referer" '
                  '"$http_user_agent"';

access_log /var/log/nginx/access.log simple;

error_log /var/log/nginx/error.log warn;

server {
    listen 80;
    server_name localhost eltorto.ru www.eltorto.ru;
    # для https server_name eltorto.ru www.eltorto.ru;
    # Все запросы на HTTPS
    #return 301 https://$server_name$request_uri;

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/ {
        proxy_pass http://api:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /swagger {
        proxy_pass http://api:8080/swagger;
        proxy_set_header Host $host;
    }
}